import type {
  Song,
  Movie,
  Tree,
  PlantingLocation,
  TreatIdea,
  Meal,
  Gemstone,
  Coin,
  RadioStation,
  AncientCivilization,
  Poetry,
  Equation,
  RareProp,
  ChemistryEpisode,
} from './types'

export const modernSongs: Song[] = [
  {
    id: 'song-001',
    title: 'Take On Me',
    artist: 'a-ha',
    year: 1985,
    youtubeUrl: 'https://www.youtube.com/watch?v=djV11Xbc914',
    imageUrl: 'https://i.ytimg.com/vi/djV11Xbc914/maxresdefault.jpg',
    genreTags: ['synth-pop', '80s', 'new wave'],
    durationSec: 225,
    value: 0.35,
    context: 'Iconic 80s synth-pop hit with groundbreaking rotoscope animation music video.',
    sources: [
      {
        title: 'a-ha - Take On Me (Official Video)',
        url: 'https://www.youtube.com/watch?v=djV11Xbc914',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'song-002',
    title: 'Sweet Child O\' Mine',
    artist: 'Guns N\' Roses',
    year: 1987,
    youtubeUrl: 'https://www.youtube.com/watch?v=1w7OgIMMRc4',
    imageUrl: 'https://i.ytimg.com/vi/1w7OgIMMRc4/maxresdefault.jpg',
    genreTags: ['rock', 'hard rock', '80s'],
    durationSec: 356,
    value: 0.40,
    context: 'Epic rock ballad with one of the most recognizable guitar riffs in history.',
    sources: [
      {
        title: 'Guns N\' Roses - Sweet Child O\' Mine (Official Music Video)',
        url: 'https://www.youtube.com/watch?v=1w7OgIMMRc4',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'song-003',
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    year: 1983,
    youtubeUrl: 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y',
    imageUrl: 'https://i.ytimg.com/vi/Zi_XLOBDo_Y/maxresdefault.jpg',
    genreTags: ['pop', 'funk', '80s'],
    durationSec: 294,
    value: 0.45,
    context: 'Legendary pop track that defined a generation with its moonwalk debut.',
    sources: [
      {
        title: 'Michael Jackson - Billie Jean (Official Video)',
        url: 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'song-004',
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    year: 1991,
    youtubeUrl: 'https://www.youtube.com/watch?v=hTWKbfoikeg',
    imageUrl: 'https://i.ytimg.com/vi/hTWKbfoikeg/maxresdefault.jpg',
    genreTags: ['grunge', 'rock', '90s'],
    durationSec: 301,
    value: 0.38,
    context: 'Generation-defining grunge anthem that revolutionized rock music in the 90s.',
    sources: [
      {
        title: 'Nirvana - Smells Like Teen Spirit (Official Music Video)',
        url: 'https://www.youtube.com/watch?v=hTWKbfoikeg',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'song-005',
    title: 'Thriller',
    artist: 'Michael Jackson',
    year: 1982,
    youtubeUrl: 'https://www.youtube.com/watch?v=sOnqjkJTMaA',
    imageUrl: 'https://i.ytimg.com/vi/sOnqjkJTMaA/maxresdefault.jpg',
    genreTags: ['pop', 'funk', '80s', 'horror'],
    durationSec: 357,
    value: 0.50,
    context: 'Most iconic music video ever made, transformed MTV and popular music.',
    sources: [
      {
        title: 'Michael Jackson - Thriller (Official 4K Video)',
        url: 'https://www.youtube.com/watch?v=sOnqjkJTMaA',
        retrievedAt: '2024-01-15',
      },
    ],
  },
]

export const trees: Tree[] = [
  {
    id: 'tree-001',
    commonName: 'Eastern Redbud',
    scientificName: 'Cercis canadensis',
    hardinessZones: ['4', '5', '6', '7', '8', '9'],
    nativeRegions: ['Eastern North America'],
    careNotes: 'Plant in full sun to partial shade. Tolerates various soil types but prefers well-drained soil. Water regularly until established. Blooms profuse pink-purple flowers in early spring before leaves emerge.',
    ecologicalValue: 'Excellent early spring nectar source for pollinators. Provides food for birds and butterflies. Nitrogen-fixing properties improve soil health.',
    sources: [
      { title: 'USDA Plant Database', url: 'https://plants.usda.gov/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'tree-002',
    commonName: 'Flowering Dogwood',
    scientificName: 'Cornus florida',
    hardinessZones: ['5', '6', '7', '8', '9'],
    nativeRegions: ['Eastern United States'],
    careNotes: 'Prefers partial shade and acidic, well-drained soil. Mulch to keep roots cool. Four-season interest with spring flowers, summer foliage, fall color, and winter berries.',
    ecologicalValue: 'Critical food source for over 75 bird species. Berries high in fat content for migrating birds. Supports native butterflies and moths.',
    sources: [
      { title: 'Arbor Day Foundation', url: 'https://www.arborday.org/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'tree-003',
    commonName: 'American Persimmon',
    scientificName: 'Diospyros virginiana',
    hardinessZones: ['4', '5', '6', '7', '8', '9'],
    nativeRegions: ['Southeastern United States'],
    careNotes: 'Adaptable to various soils. Drought-tolerant once established. Produces sweet, edible fruit after first frost. Plant both male and female trees for fruit production.',
    ecologicalValue: 'Fruit provides food for wildlife including deer, raccoons, and birds. Deep taproot prevents erosion and improves soil structure.',
    sources: [
      { title: 'Native Plant Society', url: 'https://www.wildflower.org/', retrievedAt: '2024-01-15' },
    ],
  },
]

export const plantingLocations: PlantingLocation[] = [
  {
    id: 'location-001',
    name: 'Community Park',
    region: 'Urban Green Space',
    climateTags: ['temperate', 'four-season'],
    permitNotes: 'Contact local parks department. Most municipalities encourage native tree planting in designated areas. Apply for free tree program or community planting events.',
    sources: [
      { title: 'TreeFolks Community Planting', url: 'https://www.treefolks.org/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'location-002',
    name: 'Backyard Habitat',
    region: 'Private Residential',
    climateTags: ['varies-by-region'],
    permitNotes: 'No permit required for private property in most areas. Check HOA restrictions and utility line locations (call 811 before digging). Maintain 10ft clearance from structures.',
    sources: [
      { title: 'National Wildlife Federation Habitat', url: 'https://www.nwf.org/garden', retrievedAt: '2024-01-15' },
    ],
  },
]

export const treats: TreatIdea[] = [
  {
    id: 'treat-001',
    name: 'Pawpaw Fruit',
    type: 'fruit',
    originCountry: 'United States',
    seasonality: 'Late Summer to Early Fall',
    flavorProfile: 'Tropical banana-mango custard flavor with creamy texture. North America\'s largest native edible fruit, often called "poor man\'s banana."',
    whereToBuyNotes: 'Find at specialty farmers markets in September. Or forage from native trees in Eastern US forests (with permission). Can order online from specialty fruit suppliers.',
    sources: [
      { title: 'Kentucky State University Pawpaw Research', url: 'https://www.kysu.edu/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'treat-002',
    name: 'Mayhaw Jelly',
    type: 'dessert',
    originCountry: 'United States',
    seasonality: 'Spring (berries May)',
    flavorProfile: 'Tart, cranberry-like flavor made into premium jelly. Southern delicacy from wetland hawthorn trees. Prized for unique flavor and limited availability.',
    whereToBuyNotes: 'Purchase from Southern artisan producers, especially Louisiana and Texas. Check specialty food shops or order from regional producers online.',
    sources: [
      { title: 'Southern Foodways Alliance', url: 'https://www.southernfoodways.org/', retrievedAt: '2024-01-15' },
    ],
  },
]

export const meals: Meal[] = [
  {
    id: 'meal-001',
    mealName: 'Country-Style Pot Roast with Vegetables',
    cuisineRegion: 'American Heartland',
    components: ['Chuck roast', 'Carrots', 'Potatoes', 'Onions', 'Beef gravy'],
    recipeText: 'Season 3-4lb chuck roast with salt and pepper. Sear all sides in Dutch oven. Add quartered potatoes, carrots, and onions. Pour in 2 cups beef broth. Cover and braise at 325°F for 3 hours until fork-tender. Make gravy from pan drippings.',
    historyNotes: 'Classic Sunday dinner tradition dating to homestead era. Slow-cooking tough cuts made affordable meat tender. One-pot meal conserved fuel and fed large families.',
    variants: ['Mississippi Pot Roast (add pepperoncini)', 'Yankee Pot Roast (add turnips)', 'French-style (with red wine)'],
    sources: [
      { title: 'Fannie Farmer Cookbook Archive', url: 'https://archive.org/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'meal-002',
    mealName: 'Chicken and Dumplings',
    cuisineRegion: 'Southern United States',
    components: ['Whole chicken', 'Flour dumplings', 'Chicken stock', 'Vegetables', 'Cream'],
    recipeText: 'Simmer whole chicken with celery, onion, carrot until tender (90 min). Remove chicken, strain broth. Shred meat. Return broth to simmer. Drop spoonfuls of dumpling dough (flour, baking powder, milk, salt). Cover and steam 15 minutes. Add chicken back. Finish with cream.',
    historyNotes: 'Depression-era comfort food that stretched one chicken into hearty meal for families. Dumplings added bulk. Regional variations include rolled vs dropped dumplings.',
    variants: ['Rolled flat dumplings (Pennsylvania Dutch)', 'Drop biscuit style (Deep South)', 'Herb-infused (modern)'],
    sources: [
      { title: 'Southern Living Recipe Archive', url: 'https://www.southernliving.com/', retrievedAt: '2024-01-15' },
    ],
  },
]

export const gemstones: Gemstone[] = [
  {
    id: 'gem-001',
    name: 'Arkansas Quartz Crystal',
    type: 'crystal',
    mohs: 7,
    colors: ['Clear', 'White', 'Smoky'],
    formation: 'Hydrothermal crystals formed 300 million years ago in Ouachita Mountains. Recognized as Arkansas state mineral.',
    whereFoundRegions: ['Arkansas (Ouachita Mountains)', 'Hot Springs area'],
    ethicalCollectingNotes: 'Visit fee-dig crystal mines where you keep what you find. Mines like Wegner Crystal Mines and Ron Coleman Mining allow ethical collecting. Never collect from protected land without permission.',
    whereToBuyNotes: 'Purchase from Arkansas crystal mines directly, or reputable mineral shows. Expect $10-50 for nice specimens. Ensure sourced from legal dig sites.',
    sources: [
      { title: 'Arkansas Geological Survey', url: 'https://www.geology.arkansas.gov/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'gem-002',
    name: 'Lake Superior Agate',
    type: 'gem',
    mohs: 6.5,
    colors: ['Red', 'Orange', 'Yellow', 'Brown banding'],
    formation: 'Volcanic activity 1.1 billion years ago. Iron oxidation creates striking red bands. Glaciers distributed them across Great Lakes region.',
    whereFoundRegions: ['Minnesota', 'Wisconsin', 'Michigan (Lake Superior shores)'],
    ethicalCollectingNotes: 'Collect from public beaches and gravel pits with permission. Minnesota state gemstone. Best hunting after storms expose new material.',
    whereToBuyNotes: 'Find at rock shops in Minnesota/Wisconsin. Prices range $5-100+ depending on size and banding. Look for authentic Great Lakes origin certification.',
    sources: [
      { title: 'Minnesota DNR Mineral Resources', url: 'https://www.dnr.state.mn.us/', retrievedAt: '2024-01-15' },
    ],
  },
]

export const coins: Coin[] = [
  {
    id: 'coin-001',
    name: '1916-D Mercury Dime',
    issuerCountry: 'United States',
    denomination: '10 cents',
    year: 1916,
    mint: 'Denver',
    mintage: 264000,
    composition: '90% Silver, 10% Copper',
    diameterMm: 17.9,
    coinTypeTags: ['key-date', 'low-mintage', 'mercury-dime'],
    historyText: 'First year of Mercury dime series designed by Adolph Weinman. Denver mint produced only 264,000 making it the key date of the series. Liberty wears winged cap symbolizing freedom of thought.',
    collectorNotes: 'Most valuable coin in Mercury dime series. Even well-worn examples valuable. Beware of counterfeits. Authenticate before purchasing. Values range from $1,000+ in Good condition to $30,000+ in Mint State.',
    whereToFindLinks: [
      'https://www.pcgs.com/coinfacts/coin/1916-d-10c/4906',
      'https://www.ngccoin.com/coin-explorer/mercury-dimes-1916-1945/',
    ],
    sources: [
      { title: 'PCGS CoinFacts', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'coin-002',
    name: '1909-S VDB Lincoln Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1909,
    mint: 'San Francisco',
    mintage: 484000,
    composition: '95% Copper, 5% Tin and Zinc',
    diameterMm: 19,
    coinTypeTags: ['key-date', 'lincoln-cent', 'vdb', 'low-mintage'],
    historyText: 'First year of Lincoln cent. Designer Victor David Brenner\'s initials (VDB) on reverse caused controversy, leading to removal mid-year. San Francisco mint produced limited quantity before change.',
    collectorNotes: 'Holy grail for Lincoln cent collectors. Lowest mintage of VDB varieties. Check reverse for clear VDB initials at bottom. Values $700+ circulated, $1,500+ uncirculated. Most common date in search for valuable pennies.',
    whereToFindLinks: [
      'https://www.pcgs.com/coinfacts/coin/1909-s-vdb-1c/2426',
    ],
    sources: [
      { title: 'NGC Coin Explorer', url: 'https://www.ngccoin.com/', retrievedAt: '2024-01-15' },
    ],
  },
]

export const modernMovies: Movie[] = [
  {
    id: 'movie-001',
    title: 'There Will Be Blood',
    year: 2007,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_.jpg',
    runtimeMin: 158,
    rating: 'R',
    value: 0.50,
    synopsis: 'Paul Thomas Anderson\'s masterpiece starring Daniel Day-Lewis in his Oscar-winning role as an ambitious oil prospector in early 20th century California. A towering epic about greed, family, and the corrupting influence of wealth.',
    sources: [
      {
        title: 'There Will Be Blood - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-002',
    title: 'The Mask of Zorro',
    year: 1998,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BODJiZTAzMmYtMjdkMC00ZGJiLWEzNjctMTA5MTA1Y2YzNTZmXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
    runtimeMin: 136,
    rating: 'PG-13',
    value: 0.45,
    synopsis: 'A pulse-pounding action-adventure featuring Antonio Banderas and Anthony Hopkins. The aging Don Diego de la Vega trains a young thief to become the new Zorro and together they fight against a corrupt governor.',
    sources: [
      {
        title: 'The Mask of Zorro - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-003',
    title: 'Labyrinth',
    year: 1986,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BMjM2MDE4OTQwOV5BMl5BanBnXkFtZTgwNjgxMTg2NzE@._V1_.jpg',
    runtimeMin: 101,
    rating: 'PG',
    value: 0.42,
    synopsis: 'The Jim Henson cult classic starring David Bowie as Jareth the Goblin King. A teenage girl must navigate a magical labyrinth to rescue her baby brother from the goblin kingdom.',
    sources: [
      {
        title: 'Labyrinth - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-004',
    title: 'Crazy, Stupid, Love',
    year: 2011,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTg2MjkwMTM0NF5BMl5BanBnXkFtZTcwMzc4NDg2NQ@@._V1_.jpg',
    runtimeMin: 118,
    rating: 'PG-13',
    value: 0.43,
    synopsis: 'A widely acclaimed romantic comedy with an ensemble cast including Steve Carell, Ryan Gosling, Julianne Moore, and Emma Stone. A middle-aged husband learns to navigate the dating world after his wife asks for a divorce.',
    sources: [
      {
        title: 'Crazy, Stupid, Love - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-005',
    title: 'No Country for Old Men',
    year: 2007,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_.jpg',
    runtimeMin: 122,
    rating: 'R',
    value: 0.48,
    synopsis: 'The Coen brothers\' tense neo-Western thriller starring Javier Bardem, Josh Brolin, and Tommy Lee Jones. A hunter stumbles upon a drug deal gone wrong and must evade a relentless killer.',
    sources: [
      {
        title: 'No Country for Old Men - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-006',
    title: 'Breakfast at Tiffany\'s',
    year: 1961,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BYWQwOWVkMGItMDU3Yy00YzM5LTk3ZDMtMjI5MmViY2YxODQwXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg',
    runtimeMin: 115,
    rating: 'NR',
    value: 0.46,
    synopsis: 'Audrey Hepburn\'s iconic performance as Holly Golightly, a New York socialite who befriends a struggling writer. A timeless classic featuring unforgettable fashion and Henry Mancini\'s "Moon River".',
    sources: [
      {
        title: 'Breakfast at Tiffany\'s - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-007',
    title: 'The Report',
    year: 2019,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BYjFlOTBlZTQtMWQ4Zi00MmUzLTg3NDQtNGM5NjVjNWIzYTY4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
    runtimeMin: 119,
    rating: 'R',
    value: 0.44,
    synopsis: 'A gripping political drama starring Adam Driver as a Senate staffer investigating the CIA\'s use of torture following 9/11. Based on true events.',
    sources: [
      {
        title: 'The Report - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-008',
    title: 'Finding Neverland',
    year: 2004,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTUzNjQ4NzU0NV5BMl5BanBnXkFtZTcwMjAyNTQyMw@@._V1_.jpg',
    runtimeMin: 106,
    rating: 'PG',
    value: 0.41,
    synopsis: 'The biographical story behind Peter Pan. Johnny Depp stars as J.M. Barrie, whose relationship with a widow and her four sons inspires him to create his most famous work.',
    sources: [
      {
        title: 'Finding Neverland - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-009',
    title: 'The Notebook',
    year: 2004,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTk3OTM5Njg5M15BMl5BanBnXkFtZTYwMzA0ODI3._V1_.jpg',
    runtimeMin: 123,
    rating: 'PG-13',
    value: 0.45,
    synopsis: 'The quintessential romantic drama based on the Nicholas Sparks novel. Ryan Gosling and Rachel McAdams star in this epic love story spanning decades.',
    sources: [
      {
        title: 'The Notebook - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-010',
    title: 'Face/Off',
    year: 1997,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BNzMzMzM0NTE1OV5BMl5BanBnXkFtZTcwODg4MTIzMQ@@._V1_.jpg',
    runtimeMin: 138,
    rating: 'R',
    value: 0.47,
    synopsis: 'John Woo\'s high-octane action thriller starring Nicolas Cage and John Travolta. An FBI agent and terrorist switch faces in a deadly game of cat and mouse.',
    sources: [
      {
        title: 'Face/Off - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-011',
    title: 'Surviving the Game',
    year: 1994,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTkzMTE2Nzk5N15BMl5BanBnXkFtZTcwNTI1MzI5Mw@@._V1_.jpg',
    runtimeMin: 96,
    rating: 'R',
    value: 0.40,
    synopsis: 'An intense cult favorite starring Ice-T as a homeless man who becomes the target of wealthy hunters in a deadly game of survival.',
    sources: [
      {
        title: 'Surviving the Game - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-012',
    title: 'The Infiltrator',
    year: 2016,
    youtubeUrl: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTc1NDcwNDA2MV5BMl5BanBnXkFtZTgwNTA4NjIwOTE@._V1_.jpg',
    runtimeMin: 127,
    rating: 'R',
    value: 0.43,
    synopsis: 'Bryan Cranston stars as a U.S. Customs agent who goes undercover to infiltrate Pablo Escobar\'s drug cartel. Based on true events.',
    sources: [
      {
        title: 'The Infiltrator - YouTube Free Movies',
        url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D',
        retrievedAt: '2026-04-15',
      },
    ],
  },
  {
    id: 'movie-013',
    title: 'Back to the Future',
    year: 1985,
    youtubeUrl: 'https://www.youtube.com/watch?v=qvsgGtivCgs',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
    runtimeMin: 116,
    rating: 'PG',
    value: 0.40,
    synopsis: 'Marty McFly accidentally travels back to 1955 in a time-traveling DeLorean. Quintessential 80s adventure featuring rare clocks and time-travel props that collectors seek.',
    sources: [
      {
        title: 'Back to the Future - Trailer',
        url: 'https://www.youtube.com/watch?v=qvsgGtivCgs',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'movie-014',
    title: 'The Terminator',
    year: 1984,
    youtubeUrl: 'https://www.youtube.com/watch?v=k64P4l2Wmeg',
    imageUrl: 'https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
    runtimeMin: 107,
    rating: 'R',
    value: 0.40,
    synopsis: 'A family heads to an isolated hotel where an evil presence drives the father toward violence. Kubrick\'s masterpiece of psychological horror.',
    sources: [
      {
        title: 'The Shining - Trailer',
        url: 'https://www.youtube.com/watch?v=5Cb3ik6zP2I',
        retrievedAt: '2024-01-15',
      },
    ],
  },
]

export const radioStations: RadioStation[] = [
  {
    id: 'radio-001',
    name: 'BBC Radio 1',
    country: 'United Kingdom',
    city: 'London',
    genre: 'Pop, Rock, Electronic',
    language: 'English',
    streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one',
    website: 'https://www.bbc.co.uk/radio1',
    description: 'The UK\'s most popular radio station for new music and entertainment. Broadcasting since 1967, Radio 1 has launched countless music careers and shaped British pop culture.',
    frequency: '97-99 FM',
    established: 1967,
  },
  {
    id: 'radio-002',
    name: 'KEXP 90.3 FM',
    country: 'United States',
    city: 'Seattle',
    genre: 'Alternative, Indie, World Music',
    language: 'English',
    streamUrl: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3',
    website: 'https://www.kexp.org',
    description: 'Independent listener-supported radio championing music discovery. Known for eclectic programming and supporting emerging artists worldwide.',
    frequency: '90.3 FM',
    established: 1972,
  },
  {
    id: 'radio-003',
    name: 'Radio France Internationale',
    country: 'France',
    city: 'Paris',
    genre: 'News, World Music, Talk',
    language: 'French, English, Multiple',
    streamUrl: 'https://rfienglish64k.ice.infomaniak.ch/rfienglish-64.mp3',
    website: 'https://www.rfi.fr',
    description: 'Global news and cultural radio broadcasting in 16 languages. Offers unique perspectives on world events and francophone culture.',
    frequency: 'Various',
    established: 1975,
  },
  {
    id: 'radio-004',
    name: 'NTS Radio',
    country: 'United Kingdom',
    city: 'London',
    genre: 'Underground, Electronic, Experimental',
    language: 'English',
    streamUrl: 'https://stream-relay-geo.ntslive.net/stream',
    website: 'https://www.nts.live',
    description: 'Cutting-edge online radio featuring underground music from around the world. 1000+ shows from global DJs and music curators broadcasting 24/7.',
    established: 2011,
  },
  {
    id: 'radio-005',
    name: 'Worldwide FM',
    country: 'United Kingdom',
    city: 'London',
    genre: 'Global Bass, Reggae, Hip-Hop, Jazz',
    language: 'English',
    streamUrl: 'https://worldwidefm.out.airtime.pro/worldwidefm_a',
    website: 'https://worldwidefm.net',
    description: 'Founded by Gilles Peterson, this station explores music from around the globe with a focus on deep cuts and cultural connections.',
    established: 2016,
  },
  {
    id: 'radio-006',
    name: 'Radio Garden (Tokyo)',
    country: 'Japan',
    city: 'Tokyo',
    genre: 'J-Pop, Rock, Traditional',
    language: 'Japanese',
    streamUrl: 'https://radio.garden/api/ara/content/listen/HJgKBPHx/channel.mp3',
    website: 'https://radio.garden',
    description: 'Experience Tokyo\'s vibrant radio scene featuring the latest J-Pop hits, traditional music, and contemporary culture from one of the world\'s most dynamic cities.',
    frequency: 'Various FM',
  },
]

export const ancientCivilizations: AncientCivilization[] = [
  {
    id: 'civ-001',
    name: 'Ancient Egypt',
    period: '3100 BCE - 30 BCE',
    region: 'Nile River Valley, North Africa',
    storyTitle: 'The Building of the Great Pyramid',
    storyText: 'During the reign of Pharaoh Khufu, thousands of skilled workers gathered at Giza to construct what would become one of the Seven Wonders of the Ancient World. Contrary to popular myth, these were not slaves but paid laborers who lived in nearby workers\' villages. Using copper tools, wooden sledges, and ingenious ramp systems, they precisely cut and moved 2.3 million limestone blocks, some weighing 15 tons. The pyramid\'s sides align almost perfectly with the cardinal directions, demonstrating sophisticated astronomical knowledge. For over 20 years, workers labored in three-month shifts, fed by a complex supply system that included bakeries producing thousands of loaves daily. The Great Pyramid stood as the world\'s tallest structure for nearly 4,000 years.',
    significance: 'The pyramids represent humanity\'s earliest monumental architecture and demonstrate advanced mathematical, engineering, and organizational capabilities that influenced all subsequent civilizations.',
    artifacts: ['Pyramids of Giza', 'Rosetta Stone', 'Book of the Dead', 'Tutankhamun\'s Tomb', 'Sphinx'],
    sources: [
      { title: 'The Archaeology of Ancient Egypt', url: 'https://archive.org/', retrievedAt: '2024-01-15' },
      { title: 'British Museum Egyptian Collection', url: 'https://www.britishmuseum.org/collection/egypt', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'civ-002',
    name: 'Mesopotamia (Sumer)',
    period: '4500 BCE - 1900 BCE',
    region: 'Tigris-Euphrates River Valley, Iraq',
    storyTitle: 'The First Written Words',
    storyText: 'In the city of Uruk around 3200 BCE, a Sumerian scribe pressed a reed stylus into a soft clay tablet to record grain transactions for the temple. This moment marked the birth of writing itself. What began as simple pictograms for counting sheep and measuring grain evolved into cuneiform, a sophisticated writing system capable of expressing complex ideas, laws, and literature. The Epic of Gilgamesh, humanity\'s oldest known story, was written in cuneiform. Sumerian scribes underwent years of training in special schools called edubbas. They invented not just writing, but also the wheel, irrigation systems, the 60-minute hour, and the 360-degree circle. Their administrative innovations—contracts, receipts, and legal codes—formed the foundation of civilization itself.',
    significance: 'Sumer gave humanity writing, the wheel, mathematics, astronomy, and the first cities, establishing the template for all complex societies.',
    artifacts: ['Cuneiform Tablets', 'Standard of Ur', 'Epic of Gilgamesh', 'Ziggurat of Ur', 'Royal Game of Ur'],
    sources: [
      { title: 'Ancient Mesopotamia Portal', url: 'https://www.mesopotamia.co.uk/', retrievedAt: '2024-01-15' },
      { title: 'Penn Museum Mesopotamian Collection', url: 'https://www.penn.museum/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'civ-003',
    name: 'Indus Valley Civilization',
    period: '3300 BCE - 1300 BCE',
    region: 'Pakistan, Northwest India',
    storyTitle: 'The Mystery of Mohenjo-daro',
    storyText: 'In the city of Mohenjo-daro, one of the ancient world\'s most advanced urban centers, citizens enjoyed luxuries that wouldn\'t return to most of the world for millennia. Every house had access to a sophisticated drainage system with covered sewers running beneath brick-paved streets. Public baths, including the famous Great Bath, demonstrated an emphasis on ritual cleanliness. The city was laid out in a precise grid pattern with standardized brick sizes. Homes featured private wells and bathrooms with some of history\'s first toilets. Yet mysteriously, no palaces or temples have been found—suggesting a remarkably egalitarian society. Their writing system remains undeciphered, leaving their stories locked in thousands of mysterious seals. Around 1900 BCE, the civilization declined, possibly due to climate change, leaving behind ghost cities that wouldn\'t be rediscovered for 4,000 years.',
    significance: 'The Indus Valley Civilization demonstrated advanced urban planning, sanitation, and standardization that rivals modern cities, yet remains one of history\'s greatest mysteries.',
    artifacts: ['Dancing Girl bronze', 'Priest-King sculpture', 'Indus seals', 'Standardized weights', 'Great Bath of Mohenjo-daro'],
    sources: [
      { title: 'Harappa Archaeological Research Project', url: 'https://www.harappa.com/', retrievedAt: '2024-01-15' },
      { title: 'Ancient Indus Valley Studies', url: 'https://archive.org/', retrievedAt: '2024-01-15' },
    ],
  },
]

export const poetry: Poetry[] = [
  {
    id: 'poetry-001',
    title: 'The Road Not Taken',
    poet: 'Robert Frost',
    year: 1916,
    era: 'Modernist',
    text: 'Two roads diverged in a yellow wood, / And sorry I could not travel both / And be one traveler, long I stood / And looked down one as far as I could / To where it bent in the undergrowth; / Then took the other, as just as fair, / And having perhaps the better claim, / Because it was grassy and wanted wear; / Though as for that the passing there / Had worn them really about the same...',
    analysis: 'Often misinterpreted as celebrating bold individualism, Frost\'s poem is actually ironic—the speaker admits both paths were "really about the same" yet will later claim his choice "made all the difference." It\'s about how we construct narratives of our lives.',
    significance: 'One of America\'s most famous poems, it explores themes of choice, regret, and the stories we tell ourselves about the paths we take.',
    sources: [
      { title: 'Poetry Foundation - Robert Frost', url: 'https://www.poetryfoundation.org/poets/robert-frost', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'poetry-002',
    title: 'Still I Rise',
    poet: 'Maya Angelou',
    year: 1978,
    era: 'Contemporary',
    text: 'You may write me down in history / With your bitter, twisted lies, / You may trod me in the very dirt / But still, like dust, I\'ll rise. / Does my sassiness upset you? / Why are you beset with gloom? / \'Cause I walk like I\'ve got oil wells / Pumping in my living room...',
    analysis: 'A defiant celebration of resilience in the face of oppression. Angelou uses powerful imagery and rhythmic repetition to create an anthem of survival and triumph that resonates across all struggles for dignity.',
    significance: 'This poem became an anthem for the civil rights movement and continues to inspire oppressed people worldwide with its message of unconquerable spirit.',
    sources: [
      { title: 'Poetry Foundation - Maya Angelou', url: 'https://www.poetryfoundation.org/poets/maya-angelou', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'poetry-003',
    title: 'Do Not Go Gentle Into That Good Night',
    poet: 'Dylan Thomas',
    year: 1951,
    era: 'Modernist',
    text: 'Do not go gentle into that good night, / Old age should burn and rave at close of day; / Rage, rage against the dying of the light. / Though wise men at their end know dark is right, / Because their words had forked no lightning they / Do not go gentle into that good night...',
    analysis: 'Written for Thomas\'s dying father, this villanelle uses its circular structure to mirror the speaker\'s desperate plea. The poem celebrates fighting against death with passion rather than accepting it peacefully.',
    significance: 'One of the most powerful poems about mortality, it has become a cultural touchstone referenced in everything from medicine to space exploration.',
    sources: [
      { title: 'Poetry Foundation - Dylan Thomas', url: 'https://www.poetryfoundation.org/poets/dylan-thomas', retrievedAt: '2024-01-15' },
    ],
  },
]

export const equations: Equation[] = [
  {
    id: 'eq-001',
    name: 'Einstein\'s Mass-Energy Equivalence',
    field: 'physics',
    formula: 'E = mc²',
    description: 'Energy equals mass times the speed of light squared. This deceptively simple equation reveals that mass and energy are interchangeable—different forms of the same thing.',
    discoverer: 'Albert Einstein',
    year: 1905,
    applications: ['Nuclear power generation', 'Atomic weapons', 'PET scans in medicine', 'Stellar fusion understanding', 'Particle physics'],
    significance: 'Revolutionized physics by showing mass can be converted to energy, explaining stellar fusion and enabling nuclear technology. Fundamentally changed our understanding of the universe.',
    sources: [
      { title: 'Einstein\'s 1905 Paper', url: 'https://archive.org/', retrievedAt: '2024-01-15' },
      { title: 'Physics Today - E=mc² Explained', url: 'https://physicstoday.scitation.org/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'eq-002',
    name: 'Schrödinger Equation',
    field: 'physics',
    formula: 'iℏ∂Ψ/∂t = ĤΨ',
    description: 'The fundamental equation of quantum mechanics describing how the quantum state of a system evolves over time. Ψ (psi) is the wave function containing all information about a quantum system.',
    discoverer: 'Erwin Schrödinger',
    year: 1926,
    applications: ['Semiconductor design', 'Quantum computing', 'Molecular chemistry', 'Laser technology', 'Materials science'],
    significance: 'Foundation of quantum mechanics, enabling the technology revolution including transistors, LEDs, and modern electronics. Describes the probabilistic nature of reality at the smallest scales.',
    sources: [
      { title: 'Quantum Mechanics Foundation', url: 'https://www.physics.org/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'eq-003',
    name: 'Navier-Stokes Equations',
    field: 'physics',
    formula: 'ρ(∂v/∂t + v·∇v) = -∇p + μ∇²v + f',
    description: 'Describes the motion of fluids (liquids and gases). These partial differential equations account for viscosity, pressure, and external forces affecting fluid flow.',
    discoverer: 'Claude-Louis Navier, George Gabriel Stokes',
    year: 1822,
    applications: ['Weather prediction', 'Aircraft design', 'Blood flow modeling', 'Ocean current simulation', 'Climate modeling'],
    significance: 'Essential for understanding fluid dynamics. Unsolved mathematical aspects are one of the Millennium Prize Problems with a $1M reward.',
    sources: [
      { title: 'Fluid Dynamics Research', url: 'https://www.cambridge.org/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'eq-004',
    name: 'Ideal Gas Law',
    field: 'chemistry',
    formula: 'PV = nRT',
    description: 'Relates pressure (P), volume (V), amount of gas in moles (n), ideal gas constant (R), and temperature (T). Describes the behavior of ideal gases.',
    discoverer: 'Émile Clapeyron (combined earlier laws)',
    year: 1834,
    applications: ['Chemical engineering', 'Scuba diving calculations', 'Weather balloons', 'Engine design', 'HVAC systems'],
    significance: 'Fundamental equation in chemistry and engineering, allowing prediction of gas behavior under different conditions.',
    sources: [
      { title: 'Chemistry LibreTexts', url: 'https://chem.libretexts.org/', retrievedAt: '2024-01-15' },
    ],
  },
]

export const rareProps: RareProp[] = [
  {
    id: 'prop-001',
    name: 'Flux Capacitor Clock',
    category: 'Time-Travel Props',
    description: 'The iconic Y-shaped device that makes time travel possible in the DeLorean. Features three glowing chambers arranged in a distinctive triangular pattern with pulsing LEDs.',
    movieAppearances: ['Back to the Future (1985)', 'Back to the Future Part II (1989)', 'Back to the Future Part III (1990)'],
    historicalSignificance: 'One of cinema\'s most recognizable sci-fi props. The design became synonymous with time travel itself. Original props are extremely rare, with replicas highly sought after by collectors.',
    estimatedValue: '$1,000-$50,000+ (depending on authenticity and provenance)',
    ebaySearchUrl: 'https://www.ebay.com/sch/i.html?_nkw=flux+capacitor+prop+back+to+future',
    lastRefreshed: new Date().toISOString().split('T')[0],
    identificationTips: 'Authentic props feature three chambers with specific LED patterns. Look for documentation from Universal Pictures or production crew provenance. Most available items are high-quality replicas.',
    sources: [
      { title: 'Back to the Future Props Archive', url: 'https://www.bttf.com/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'prop-002',
    name: 'Hill Valley Clock Tower',
    category: 'Iconic Timepieces',
    description: 'The clock tower struck by lightning at precisely 10:04 PM on November 12, 1955. Central to the plot of Back to the Future, frozen in time after the lightning strike.',
    movieAppearances: ['Back to the Future (1985)', 'Back to the Future Part II (1989)', 'Back to the Future Part III (1990)'],
    historicalSignificance: 'The clock tower serves as the emotional and temporal anchor for the entire trilogy. Filmed at the real Courthouse Square at Universal Studios.',
    estimatedValue: '$50-$500 for replica models and memorabilia',
    ebaySearchUrl: 'https://www.ebay.com/sch/i.html?_nkw=hill+valley+clock+tower+back+future',
    lastRefreshed: new Date().toISOString().split('T')[0],
    identificationTips: 'Look for detailed replicas showing the clock stopped at 10:04. Official Universal Studios merchandise often includes certificates of authenticity.',
    sources: [
      { title: 'BTTF Production Design Archives', url: 'https://archive.org/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'prop-003',
    name: 'Lightyear Clock',
    category: 'Futuristic Timepieces',
    description: 'Rare vintage LED digital clocks from the 1970s-80s featuring futuristic designs that appeared in numerous sci-fi films as set dressing.',
    movieAppearances: ['Blade Runner (1982)', 'The Terminator (1984)', 'Various 80s sci-fi films'],
    historicalSignificance: 'These clocks represent the era\'s vision of the future. Models like the Lightyear Bubble Clock became icons of retrofuturism.',
    estimatedValue: '$100-$1,500 for vintage originals in working condition',
    ebaySearchUrl: 'https://www.ebay.com/sch/i.html?_nkw=vintage+LED+bubble+clock+1970s',
    lastRefreshed: new Date().toISOString().split('T')[0],
    identificationTips: 'Original 1970s LED clocks often have bubble lenses, wood grain finishes, or space-age plastic designs. Check for manufacturer marks like Spartus or Lightyear.',
    sources: [
      { title: 'Vintage Clock Collectors Guide', url: 'https://www.nawcc.org/', retrievedAt: '2024-01-15' },
    ],
  },
]

export const chemistryEpisodes: ChemistryEpisode[] = [
  {
    id: 'chem-001',
    title: 'The Science of Crystal Meth',
    series: 'Breaking Bad',
    season: 1,
    episode: 1,
    chemicalConcept: 'Methylamine synthesis and crystallization',
    description: 'Walter White applies his chemistry knowledge to synthesize high-purity methamphetamine using the pseudoephedrine reduction method, later transitioning to methylamine-based synthesis for higher yields.',
    educationalValue: 'While depicting illegal activity, the show accurately portrays chemical processes including acid-base reactions, crystallization, and the importance of purity in chemical synthesis. Demonstrates how chemistry knowledge applies to real-world scenarios (legal ones preferably!).',
    youtubeUrl: 'https://www.youtube.com/watch?v=HhesaQXLuRY',
    sources: [
      { title: 'Breaking Bad Science Consultant Interviews', url: 'https://www.acs.org/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'chem-002',
    title: 'Julius Sumner Miller: Why Is It So? - Air Pressure',
    series: 'Why Is It So?',
    season: 1,
    episode: 3,
    chemicalConcept: 'Atmospheric pressure and gas laws',
    description: 'Professor Julius Sumner Miller demonstrates the invisible force of air pressure through entertaining experiments including crushing cans, lifting water with pressure, and the famous egg-in-bottle demonstration.',
    educationalValue: 'Classic physics education showing how air pressure affects everyday life. Demonstrates the ideal gas law and pressure differentials through hands-on experiments that viewers can replicate safely.',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQjqwmF_dDI',
    sources: [
      { title: 'Julius Sumner Miller Archive', url: 'https://archive.org/', retrievedAt: '2024-01-15' },
    ],
  },
  {
    id: 'chem-003',
    title: 'The Elements of Chemistry',
    series: 'Cosmos: A Personal Voyage',
    season: 1,
    episode: 9,
    chemicalConcept: 'Stellar nucleosynthesis and the periodic table',
    description: 'Carl Sagan explains how every atom in our bodies was forged in the heart of dying stars, connecting chemistry, physics, and cosmology in a poetic exploration of our atomic origins.',
    educationalValue: 'Demonstrates how heavy elements are created through nuclear fusion in stars and supernova explosions. Shows the deep connection between astronomy and chemistry.',
    youtubeUrl: 'https://www.youtube.com/watch?v=Qe1GgnMSqOA',
    sources: [
      { title: 'Cosmos Archive', url: 'https://www.cosmos-tv.com/', retrievedAt: '2024-01-15' },
    ],
  },
]
