import type {
  RadioStation,
  AncientCivilization,
  Poetry,
  Equation,
  RareProp,
  ChemistryEpisode,
  Source,
} from './types'

export const radioStations: RadioStation[] = [
  {
    id: 'radio-001',
    name: 'BBC Radio 1',
    country: 'United Kingdom',
    city: 'London',
    genre: 'Pop, Rock, Dance',
    language: 'English',
    streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one',
    website: 'https://www.bbc.co.uk/radio1',
    description: 'The UK\'s leading contemporary music station, broadcasting since 1967.',
    frequency: '97-99 FM',
    established: 1967,
  },
  {
    id: 'radio-002',
    name: 'KEXP',
    country: 'United States',
    city: 'Seattle',
    genre: 'Alternative, Indie',
    language: 'English',
    streamUrl: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3',
    website: 'https://www.kexp.org',
    description: 'Seattle\'s legendary independent radio station featuring cutting-edge music.',
    frequency: '90.3 FM',
    established: 1972,
  },
  {
    id: 'radio-003',
    name: 'FIP',
    country: 'France',
    city: 'Paris',
    genre: 'Eclectic, Jazz, World',
    language: 'French',
    streamUrl: 'https://icecast.radiofrance.fr/fip-midfi.mp3',
    website: 'https://www.fip.fr',
    description: 'France\'s iconic eclectic music station with minimal talk and maximum diversity.',
    frequency: '105.1 FM',
    established: 1971,
  },
  {
    id: 'radio-004',
    name: 'Radio Paradise',
    country: 'United States',
    city: 'Paradise, CA',
    genre: 'Eclectic, Rock, World',
    language: 'English',
    streamUrl: 'https://stream.radioparadise.com/aac-320',
    website: 'https://www.radioparadise.com',
    description: 'Commercial-free internet radio with an eclectic blend of rock, world, electronica.',
    established: 2000,
  },
  {
    id: 'radio-005',
    name: 'NTS Radio',
    country: 'United Kingdom',
    city: 'London',
    genre: 'Experimental, Electronic, World',
    language: 'English',
    streamUrl: 'https://stream-mixtape-geo.ntslive.net/mixtape',
    website: 'https://www.nts.live',
    description: 'Global music radio broadcasting underground music from around the world.',
    established: 2011,
  },
  {
    id: 'radio-006',
    name: 'Triple J',
    country: 'Australia',
    city: 'Sydney',
    genre: 'Alternative, Indie, Hip Hop',
    language: 'English',
    streamUrl: 'https://live-radio01.mediahubaustralia.com/2TJW/mp3/',
    website: 'https://www.abc.net.au/triplej',
    description: 'Australia\'s national youth radio network, championing new Australian music.',
    frequency: '105.7 FM',
    established: 1975,
  },
  {
    id: 'radio-007',
    name: 'WFMU',
    country: 'United States',
    city: 'Jersey City',
    genre: 'Freeform, Experimental',
    language: 'English',
    streamUrl: 'https://stream0.wfmu.org/freeform-128k',
    website: 'https://wfmu.org',
    description: 'America\'s longest-running freeform radio station, fiercely independent since 1958.',
    frequency: '91.1 FM',
    established: 1958,
  },
  {
    id: 'radio-008',
    name: 'Dublab',
    country: 'United States',
    city: 'Los Angeles',
    genre: 'Electronic, Experimental, World',
    language: 'English',
    streamUrl: 'https://dublab.out.airtime.pro/dublab_a',
    website: 'https://www.dublab.com',
    description: 'Non-profit web radio collective showcasing future music from LA and beyond.',
    established: 1999,
  },
  {
    id: 'radio-009',
    name: 'Radio Nova',
    country: 'France',
    city: 'Paris',
    genre: 'World Music, Hip Hop, Electronic',
    language: 'French',
    streamUrl: 'https://novazz.ice.infomaniak.ch/novazz-128.mp3',
    website: 'https://www.nova.fr',
    description: 'Parisian station known for its urban and world music programming.',
    frequency: '101.5 FM',
    established: 1981,
  },
  {
    id: 'radio-010',
    name: 'Worldwide FM',
    country: 'United Kingdom',
    city: 'London',
    genre: 'Global Bass, Afrobeat, Reggae',
    language: 'English',
    streamUrl: 'https://worldwidefm.out.airtime.pro/worldwidefm_a',
    website: 'https://worldwidefm.net',
    description: 'Gilles Peterson\'s global music station connecting cultures through sound.',
    established: 2016,
  },
]

export const ancientCivilizations: AncientCivilization[] = [
  {
    id: 'civ-001',
    name: 'Ancient Egypt',
    period: '3100 BCE - 30 BCE',
    region: 'Nile Valley',
    storyTitle: 'The Tale of the Shipwrecked Sailor',
    storyText: 'A sailor recounts his miraculous survival on a magical island inhabited by a wise serpent. The serpent, larger than any ship, foretold the sailor\'s rescue and shared wisdom about accepting fate. When a ship arrived exactly as prophesied, the sailor offered treasures to the serpent, who refused them, saying "I am the Prince of Punt, and these riches are mine already." The serpent gave the sailor precious gifts instead, and as the ship departed, the island vanished beneath the waves forever.',
    significance: 'One of the earliest examples of Egyptian literature, this Middle Kingdom tale explores themes of divine providence, gratitude, and the transient nature of material wealth.',
    artifacts: ['Papyrus scrolls', 'Pyramids of Giza', 'Rosetta Stone', 'Tutankhamun\'s tomb'],
    sources: [
      {
        title: 'The Tale of the Shipwrecked Sailor - British Museum',
        url: 'https://www.britishmuseum.org/collection/object/Y_EA10056',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'civ-002',
    name: 'Ancient Mesopotamia',
    period: '3500 BCE - 500 BCE',
    region: 'Tigris-Euphrates Valley',
    storyTitle: 'The Epic of Gilgamesh: The Cedar Forest',
    storyText: 'Gilgamesh, king of Uruk, and his companion Enkidu journeyed to the Cedar Forest to slay the demon Humbaba and claim the sacred cedars. Despite prophetic dreams warning of danger, they pressed forward. Humbaba pleaded for mercy, but Gilgamesh struck him down. The gods, angered by this sacrilege, decreed that one of the heroes must die. Enkidu fell ill and perished, leaving Gilgamesh to confront mortality itself.',
    significance: 'The world\'s oldest known epic, exploring friendship, hubris, and the quest for immortality.',
    artifacts: ['Cuneiform tablets', 'Ziggurat of Ur', 'Code of Hammurabi', 'Ishtar Gate'],
    sources: [
      {
        title: 'The Epic of Gilgamesh - Tablet V',
        url: 'https://www.worldhistory.org/The_Epic_of_Gilgamesh/',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'civ-003',
    name: 'Maya Civilization',
    period: '2000 BCE - 1500 CE',
    region: 'Mesoamerica',
    storyTitle: 'The Hero Twins and the Lords of Death',
    storyText: 'From the Popol Vuh: The Hero Twins, Hunahpu and Xbalanque, descended to Xibalba, the underworld, to avenge their father. The Death Lords challenged them to impossible trials—surviving the House of Darkness, the House of Knives, and the House of Fire. Through cleverness and magic, the twins prevailed in each test. Finally, they tricked the Death Lords into their own demise, then ascended to the heavens as the Sun and Moon.',
    significance: 'Central creation myth of the Maya, explaining cosmic order and the triumph of life over death.',
    artifacts: ['Popol Vuh codex', 'Tikal temples', 'Mayan calendar', 'Jade death masks'],
    sources: [
      {
        title: 'Popol Vuh: The Mayan Book of the Dawn of Life',
        url: 'https://www.sacred-texts.com/nam/maya/pvgm/index.htm',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'civ-004',
    name: 'Indus Valley Civilization',
    period: '3300 BCE - 1300 BCE',
    region: 'Northwest Indian Subcontinent',
    storyTitle: 'The Mystery of Mohenjo-daro',
    storyText: 'Archaeologists discovered the remarkably planned city of Mohenjo-daro, with its advanced drainage systems, uniform bricks, and mysterious undeciphered script. Among the ruins, they found the famous "Priest-King" sculpture and countless seals depicting unknown symbols and a figure in yogic posture. The civilization vanished suddenly, leaving behind only questions: What was their language? What gods did they worship? Why did they abandon their magnificent cities?',
    significance: 'One of history\'s greatest archaeological mysteries, showcasing advanced urban planning millennia before Europe.',
    artifacts: ['Indus seals', 'Dancing Girl bronze', 'Priest-King sculpture', 'Standardized weights'],
    sources: [
      {
        title: 'Mohenjo-daro - UNESCO World Heritage',
        url: 'https://whc.unesco.org/en/list/138',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'civ-005',
    name: 'Ancient China - Shang Dynasty',
    period: '1600 BCE - 1046 BCE',
    region: 'Yellow River Valley',
    storyTitle: 'The Oracle Bones Speak',
    storyText: 'Shang kings consulted the spirits of their ancestors by carving questions onto turtle shells and ox bones, then heating them until they cracked. Diviners interpreted the patterns to answer questions about war, harvest, and sacrifice. One bone asks: "Should the king lead 3,000 men to attack the enemy?" Another pleads: "Will the drought end?" These fragments, buried for millennia, were the first to reveal the earliest form of Chinese writing.',
    significance: 'Oracle bones provided the first tangible evidence of the Shang Dynasty and the origins of Chinese characters.',
    artifacts: ['Oracle bones', 'Bronze vessels', 'Fu Hao\'s tomb treasures', 'Jade carvings'],
    sources: [
      {
        title: 'Oracle Bone Inscriptions - Chinese Text Project',
        url: 'https://ctext.org/shang-shu',
        retrievedAt: '2024-01-15',
      },
    ],
  },
]

export const rarePoetry: Poetry[] = [
  {
    id: 'poetry-001',
    title: 'The Red Wheelbarrow',
    poet: 'William Carlos Williams',
    year: 1923,
    era: 'Modernism',
    text: 'so much depends\nupon\n\na red wheel\nbarrow\n\nglazed with rain\nwater\n\nbeside the white\nchickens',
    analysis: 'Williams captures profound meaning in everyday objects through precise imagery and enjambment.',
    significance: 'Revolutionized American poetry by elevating the ordinary to the essential.',
    sources: [
      {
        title: 'Spring and All - Poetry Foundation',
        url: 'https://www.poetryfoundation.org/poems/45502/the-red-wheelbarrow',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'poetry-002',
    title: 'In a Station of the Metro',
    poet: 'Ezra Pound',
    year: 1913,
    era: 'Imagism',
    text: 'The apparition of these faces in the crowd:\nPetals on a wet, black bough.',
    analysis: 'A masterpiece of compression, capturing a fleeting moment of urban beauty through juxtaposition.',
    significance: 'Pioneering imagist poem that influenced generations of poets with its economy and precision.',
    sources: [
      {
        title: 'Imagist Poetry - Academy of American Poets',
        url: 'https://poets.org/poem/station-metro',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'poetry-003',
    title: 'Wild Geese',
    poet: 'Mary Oliver',
    year: 1986,
    era: 'Contemporary',
    text: 'You do not have to be good.\nYou do not have to walk on your knees\nfor a hundred miles through the desert repenting.\nYou only have to let the soft animal of your body\nlove what it loves.\nTell me about despair, yours, and I will tell you mine.\nMeanwhile the world goes on.',
    analysis: 'Oliver offers permission to exist without perfection, connecting human emotion to the natural world.',
    significance: 'One of the most beloved contemporary poems, offering solace and acceptance.',
    sources: [
      {
        title: 'Dream Work - Poetry Foundation',
        url: 'https://www.poetryfoundation.org/poems/43126/wild-geese',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'poetry-004',
    title: 'The Love Song of J. Alfred Prufrock (excerpt)',
    poet: 'T.S. Eliot',
    year: 1915,
    era: 'Modernism',
    text: 'Let us go then, you and I,\nWhen the evening is spread out against the sky\nLike a patient etherized upon a table;\nLet us go, through certain half-deserted streets,\nThe muttering retreats\nOf restless nights in one-handed cheap hotels',
    analysis: 'Eliot\'s revolutionary use of fragmentation and jarring imagery to capture modern alienation.',
    significance: 'Marked the arrival of high modernism in English poetry.',
    sources: [
      {
        title: 'Prufrock and Other Observations',
        url: 'https://www.poetryfoundation.org/poetrymagazine/poems/44212/the-love-song-of-j-alfred-prufrock',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'poetry-005',
    title: 'Still I Rise (excerpt)',
    poet: 'Maya Angelou',
    year: 1978,
    era: 'Contemporary',
    text: 'You may write me down in history\nWith your bitter, twisted lies,\nYou may tread me in the very dirt\nBut still, like dust, I\'ll rise.',
    analysis: 'Angelou\'s defiant anthem of resilience against oppression, blending personal and collective strength.',
    significance: 'Became an anthem of empowerment and resistance worldwide.',
    sources: [
      {
        title: 'And Still I Rise - Poetry Foundation',
        url: 'https://www.poetryfoundation.org/poems/46446/still-i-rise',
        retrievedAt: '2024-01-15',
      },
    ],
  },
]

export const famousEquations: Equation[] = [
  {
    id: 'eq-001',
    name: 'Einstein\'s Mass-Energy Equivalence',
    field: 'physics',
    formula: 'E = mc²',
    description: 'Energy equals mass times the speed of light squared',
    discoverer: 'Albert Einstein',
    year: 1905,
    applications: ['Nuclear energy', 'Particle physics', 'Cosmology'],
    significance: 'Revealed that mass and energy are interchangeable, fundamentally changing our understanding of the universe.',
    sources: [
      {
        title: 'Annus Mirabilis Papers - 1905',
        url: 'https://www.fourmilab.ch/etexts/einstein/specrel/www/',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'eq-002',
    name: 'Schrödinger Wave Equation',
    field: 'physics',
    formula: 'iℏ ∂Ψ/∂t = ĤΨ',
    description: 'Describes how quantum states evolve over time',
    discoverer: 'Erwin Schrödinger',
    year: 1926,
    applications: ['Quantum mechanics', 'Chemistry', 'Semiconductor physics'],
    significance: 'Foundation of quantum mechanics, explaining the behavior of atoms and subatomic particles.',
    sources: [
      {
        title: 'Quantisation as a Problem of Proper Values',
        url: 'https://www.nobelprize.org/prizes/physics/1933/schrodinger/facts/',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'eq-003',
    name: 'Ideal Gas Law',
    field: 'chemistry',
    formula: 'PV = nRT',
    description: 'Relates pressure, volume, temperature, and amount of gas',
    discoverer: 'Émile Clapeyron',
    year: 1834,
    applications: ['Thermodynamics', 'Chemical engineering', 'Meteorology'],
    significance: 'Fundamental equation for understanding gas behavior under various conditions.',
    sources: [
      {
        title: 'Gas Laws - Chemistry LibreTexts',
        url: 'https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)/Physical_Properties_of_Matter/States_of_Matter/Properties_of_Gases/Gas_Laws',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'eq-004',
    name: 'Maxwell\'s Equations',
    field: 'physics',
    formula: '∇·E = ρ/ε₀, ∇·B = 0, ∇×E = -∂B/∂t, ∇×B = μ₀J + μ₀ε₀∂E/∂t',
    description: 'Four equations describing electricity, magnetism, and light',
    discoverer: 'James Clerk Maxwell',
    year: 1865,
    applications: ['Electromagnetism', 'Telecommunications', 'Optics'],
    significance: 'Unified electricity and magnetism, predicted electromagnetic waves, and led to modern physics.',
    sources: [
      {
        title: 'A Dynamical Theory of the Electromagnetic Field',
        url: 'https://www.clerkmaxwellfoundation.org/html/about_maxwell.html',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'eq-005',
    name: 'Nernst Equation',
    field: 'chemistry',
    formula: 'E = E° - (RT/nF)ln(Q)',
    description: 'Relates electrode potential to concentrations in electrochemistry',
    discoverer: 'Walther Nernst',
    year: 1889,
    applications: ['Batteries', 'Fuel cells', 'Biological systems'],
    significance: 'Essential for understanding electrochemical cells and biological processes.',
    sources: [
      {
        title: 'The Nernst Equation - Nobel Prize',
        url: 'https://www.nobelprize.org/prizes/chemistry/1920/nernst/facts/',
        retrievedAt: '2024-01-15',
      },
    ],
  },
]

export const rareProps: RareProp[] = [
  {
    id: 'prop-001',
    name: 'Flux Capacitor (replica)',
    category: 'Movie Props',
    description: 'The iconic time-travel device from Back to the Future, featuring Y-shaped design with flashing lights',
    movieAppearances: ['Back to the Future (1985)', 'Back to the Future Part II (1989)', 'Back to the Future Part III (1990)'],
    historicalSignificance: 'Symbol of 1980s sci-fi cinema and the concept of time travel in popular culture.',
    estimatedValue: '$500-$5,000 (replicas), Original worth millions',
    ebaySearchUrl: 'https://www.ebay.com/sch/i.html?_nkw=flux+capacitor+back+to+the+future',
    lastRefreshed: new Date().toISOString(),
    identificationTips: 'Look for the characteristic Y-shape, LED lights, and metal construction. Original props are extremely rare.',
    sources: [
      {
        title: 'Back to the Future - The Official Website',
        url: 'https://www.backtothefuture.com',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'prop-002',
    name: 'DeLorean DMC-12 Clock',
    category: 'Collectible Timepieces',
    description: 'Time-display clocks inspired by the DeLorean from Back to the Future',
    movieAppearances: ['Back to the Future trilogy (1985-1990)'],
    historicalSignificance: 'The DeLorean became synonymous with time travel after the film\'s release.',
    estimatedValue: '$50-$300 (collectible clocks)',
    ebaySearchUrl: 'https://www.ebay.com/sch/i.html?_nkw=delorean+clock+back+to+the+future',
    lastRefreshed: new Date().toISOString(),
    identificationTips: 'Look for officially licensed products with DMC logo or Back to the Future branding.',
    sources: [
      {
        title: 'DeLorean Motor Company',
        url: 'https://delorean.com',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'prop-003',
    name: 'Vintage Laboratory Glassware',
    category: 'Scientific Props',
    description: 'Classic Erlenmeyer flasks, beakers, and retorts as seen in vintage sci-fi films',
    movieAppearances: ['Frankenstein (1931)', 'The Invisible Man (1933)', 'Young Frankenstein (1974)'],
    historicalSignificance: 'Iconic imagery of mad scientist laboratories in classic cinema.',
    estimatedValue: '$20-$200 per piece',
    ebaySearchUrl: 'https://www.ebay.com/sch/i.html?_nkw=vintage+laboratory+glassware+scientific',
    lastRefreshed: new Date().toISOString(),
    identificationTips: 'Look for Pyrex or Kimax markings, pre-1970s designs, and quality glass construction.',
    sources: [
      {
        title: 'History of Laboratory Glassware',
        url: 'https://www.corning.com/worldwide/en/innovation/corning-history.html',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'prop-004',
    name: 'Vintage Film Cameras',
    category: 'Camera Props',
    description: 'Classic film cameras like the Bolex H16 used extensively in movies about filmmaking',
    movieAppearances: ['Singin\' in the Rain (1952)', 'The Purple Rose of Cairo (1985)'],
    historicalSignificance: 'Represents the golden age of practical filmmaking before digital.',
    estimatedValue: '$300-$3,000',
    ebaySearchUrl: 'https://www.ebay.com/sch/i.html?_nkw=bolex+h16+vintage+film+camera',
    lastRefreshed: new Date().toISOString(),
    identificationTips: 'Check serial numbers, lens quality, and mechanical operation. Bolex cameras have distinctive turret lenses.',
    sources: [
      {
        title: 'Bolex Collector\'s Guide',
        url: 'https://www.bolex.co.uk',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'prop-005',
    name: 'Vintage Geiger Counter',
    category: 'Scientific Instruments',
    description: 'Classic radiation detection devices as featured in Cold War era sci-fi',
    movieAppearances: ['Them! (1954)', 'The China Syndrome (1979)', 'Silkwood (1983)'],
    historicalSignificance: 'Symbol of atomic age anxiety and nuclear science in cinema.',
    estimatedValue: '$100-$800',
    ebaySearchUrl: 'https://www.ebay.com/sch/i.html?_nkw=vintage+geiger+counter+radiation+detector',
    lastRefreshed: new Date().toISOString(),
    identificationTips: 'Look for brands like Victoreen or Ludlum. Check if functional (many are decorative only now).',
    sources: [
      {
        title: 'History of Radiation Detection',
        url: 'https://www.osti.gov/opennet',
        retrievedAt: '2024-01-15',
      },
    ],
  },
]

export const chemistryEpisodes: ChemistryEpisode[] = [
  {
    id: 'chem-001',
    title: 'Pilot',
    series: 'Breaking Bad',
    season: 1,
    episode: 1,
    chemicalConcept: 'Methamphetamine synthesis via reductive amination',
    description: 'Walter White demonstrates advanced chemistry knowledge by cooking crystal meth using pseudoephedrine reduction.',
    educationalValue: 'Shows the reality of chemical synthesis, lab safety importance, and consequences of illegal chemistry.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=breaking+bad+chemistry+explained',
    sources: [
      {
        title: 'The Science of Breaking Bad - ACS',
        url: 'https://www.acs.org/education/outreach/celebrating-chemistry-editions/2016-ncw/breaking-bad.html',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'chem-002',
    title: 'Gray Matter',
    series: 'Breaking Bad',
    season: 1,
    episode: 5,
    chemicalConcept: 'Chemical composition of the human body',
    description: 'Walt explains that humans are mostly water and common elements, pondering what makes consciousness special.',
    educationalValue: 'Explores biochemistry and the philosophical implications of our elemental composition.',
    sources: [
      {
        title: 'Elements of the Human Body',
        url: 'https://www.lenntech.com/human-body.htm',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'chem-003',
    title: 'A No-Rough-Stuff-Type Deal',
    series: 'Breaking Bad',
    season: 1,
    episode: 7,
    chemicalConcept: 'Fulminated mercury synthesis and properties',
    description: 'Walt uses mercury fulminate (explosive compound) as a weapon, demonstrating its shock-sensitive nature.',
    educationalValue: 'Illustrates explosive chemistry and the dangers of impact-sensitive compounds.',
    sources: [
      {
        title: 'Mercury Fulminate Chemistry',
        url: 'https://pubchem.ncbi.nlm.nih.gov/compound/Mercury-fulminate',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'chem-004',
    title: 'The One with the Jellyfish',
    series: 'Friends',
    season: 4,
    episode: 1,
    chemicalConcept: 'Acid-base neutralization (urine treating jellyfish stings)',
    description: 'The characters attempt to treat a jellyfish sting with urine, demonstrating a common (though debated) folk remedy.',
    educationalValue: 'Sparks discussion about acid-base chemistry and why this treatment is controversial.',
    sources: [
      {
        title: 'Jellyfish Sting Treatment - Medical Facts',
        url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1126321/',
        retrievedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 'chem-005',
    title: 'The Diesel Therapy',
    series: 'The Big Bang Theory',
    season: 1,
    episode: 8,
    chemicalConcept: 'Thermite reaction demonstration',
    description: 'Sheldon demonstrates a thermite reaction (iron oxide + aluminum) producing molten iron.',
    educationalValue: 'Shows exothermic redox reactions and thermodynamics in action.',
    sources: [
      {
        title: 'Thermite Reaction Chemistry',
        url: 'https://www.chemistryland.com/CHM130W/07-Thermo/Thermite/ThermiteReaction.htm',
        retrievedAt: '2024-01-15',
      },
    ],
  },
]
