import type { Coin } from './types'

export const expandedRareCoins: Coin[] = [
  {
    id: 'coin-003',
    name: '1933 Saint-Gaudens Double Eagle',
    issuerCountry: 'United States',
    denomination: '$20 Gold',
    year: 1933,
    mint: 'Philadelphia',
    mintage: 445500,
    composition: '90% Gold, 10% Copper',
    diameterMm: 34,
    coinTypeTags: ['gold', 'legendary', 'forbidden', 'double-eagle'],
    historyText: 'Most famous coin in U.S. history. FDR banned gold ownership in 1933. Almost all were melted. Only one legally owned - sold for $7.59 million in 2002, $18.9 million in 2021.',
    collectorNotes: 'Illegal to own except the single Fenton specimen. Any others are subject to confiscation. Most valuable coin ever auctioned.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1933-20/9177'],
    sources: [{ title: 'Smithsonian Numismatics', url: 'https://www.si.edu/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-004',
    name: '1794 Flowing Hair Silver Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 1794,
    mint: 'Philadelphia',
    mintage: 1758,
    composition: '89.24% Silver, 10.76% Copper',
    diameterMm: 39.40,
    coinTypeTags: ['silver', 'first-year', 'flowing-hair', 'legendary'],
    historyText: 'First silver dollar struck by U.S. Mint. Believed to be among first coins struck for circulation. Historic significance as foundation of American coinage.',
    collectorNotes: 'Sold for $10 million in 2013, making it most expensive coin ever. Even worn examples worth six figures. Check for proper edge lettering.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1794-1/6851'],
    sources: [{ title: 'Heritage Auctions Archives', url: 'https://www.ha.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-005',
    name: '1913 Liberty Head Nickel',
    issuerCountry: 'United States',
    denomination: '5 cents',
    year: 1913,
    mint: 'Philadelphia',
    mintage: 5,
    composition: '75% Copper, 25% Nickel',
    diameterMm: 21.2,
    coinTypeTags: ['nickel', 'pattern', 'ultra-rare', 'mystery'],
    historyText: 'Only 5 known. Never officially released. Minted secretly after series ended. Mystery surrounds creation - possibly by rogue Mint employee.',
    collectorNotes: 'One of numismatics greatest mysteries. Each of 5 specimens has own history. Worth $3-5 million. Featured in Hawaii Five-O.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1913-5c/3882'],
    sources: [{ title: 'ANA Museum Collection', url: 'https://www.money.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-006',
    name: '1804 Draped Bust Silver Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 1804,
    mint: 'Philadelphia',
    mintage: 15,
    composition: '89.24% Silver, 10.76% Copper',
    diameterMm: 39.40,
    coinTypeTags: ['silver', 'king-of-coins', 'diplomatic-gift'],
    historyText: 'King of American Coins. Actually struck in 1834-35 as diplomatic gifts. Bears 1804 date but none made that year. 15 known specimens in three classes.',
    collectorNotes: 'Class I specimens worth $4-7 million. Class II and III also extremely valuable. Verify class and authenticity with major grading service.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1804-1/6889'],
    sources: [{ title: 'Bowers Numismatic Research', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-007',
    name: '1937-D 3-Legged Buffalo Nickel',
    issuerCountry: 'United States',
    denomination: '5 cents',
    year: 1937,
    mint: 'Denver',
    mintage: 5635000,
    composition: '75% Copper, 25% Nickel',
    diameterMm: 21.2,
    coinTypeTags: ['nickel', 'error', 'variety', 'buffalo'],
    historyText: 'Famous error from over-polished die removing buffalo\'s front leg. Die polishing removed design detail to extend die life, creating valued variety.',
    collectorNotes: 'Look for completely missing front leg. Normal wear shows faint leg. Values $500-$5,000+ depending on grade. Many counterfeits exist.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1937-d-5c-3-legs/3983'],
    sources: [{ title: 'NGC Variety Guide', url: 'https://www.ngccoin.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-008',
    name: '1943 Copper Lincoln Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1943,
    mint: 'Philadelphia',
    mintage: 40,
    composition: '95% Copper, 5% Tin and Zinc',
    diameterMm: 19,
    coinTypeTags: ['cent', 'error', 'wartime', 'copper'],
    historyText: 'In 1943 pennies made of steel to save copper for WWII. About 40 copper blanks accidentally struck. One of most famous U.S. mint errors.',
    collectorNotes: 'Worth $100,000-$1,000,000+. Many steel cents copper-plated to deceive. Weight test: copper weighs 3.11g vs steel 2.7g. Magnet test: copper non-magnetic.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1943-1c/2715'],
    sources: [{ title: 'U.S. Mint Error Coins Guide', url: 'https://www.usmint.gov/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-009',
    name: '1893-S Morgan Silver Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 1893,
    mint: 'San Francisco',
    mintage: 100000,
    composition: '90% Silver, 10% Copper',
    diameterMm: 38.1,
    coinTypeTags: ['silver', 'morgan', 'key-date', 'low-mintage'],
    historyText: 'Lowest mintage of business-strike Morgan dollars. Economic depression limited production. San Francisco produced only 100,000.',
    collectorNotes: 'Most valuable regular-issue Morgan. Values $3,000+ circulated, $100,000+ high grades. Essential for Morgan dollar collection completion.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1893-s-1/7226'],
    sources: [{ title: 'Morgan Dollar Reference', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-010',
    name: '1955 Doubled Die Lincoln Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1955,
    mint: 'Philadelphia',
    mintage: 24000,
    composition: '95% Copper, 5% Tin and Zinc',
    diameterMm: 19,
    coinTypeTags: ['cent', 'error', 'doubled-die', 'lincoln'],
    historyText: 'Most famous doubled die coin. Hub doubled during die creation process. Dramatic doubling visible on date and lettering. Released into circulation despite error.',
    collectorNotes: 'Look for clear doubling on "LIBERTY" and date. Values $1,000-$20,000+ depending on grade. Easily spotted with naked eye.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1955-1c-ddo-fs-101/37911'],
    sources: [{ title: 'Doubled Die Reference', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-011',
    name: '1969-S Doubled Die Lincoln Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1969,
    mint: 'San Francisco',
    mintage: 40,
    composition: '95% Copper, 5% Zinc',
    diameterMm: 19,
    coinTypeTags: ['cent', 'error', 'doubled-die', 'ultra-rare'],
    historyText: 'Extreme doubling on obverse, especially "LIBERTY" and "IN GOD WE TRUST". Only about 40 known. Mint attempted to destroy all specimens.',
    collectorNotes: 'Values $20,000-$100,000+. Sharp doubling throughout. Beware of the more common 1969 Philadelphia doubled die (worth much less).',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1969-s-1c-ddo-fs-101/38001'],
    sources: [{ title: 'Major Doubled Dies', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-012',
    name: '1932-D Washington Quarter',
    issuerCountry: 'United States',
    denomination: '25 cents',
    year: 1932,
    mint: 'Denver',
    mintage: 436800,
    composition: '90% Silver, 10% Copper',
    diameterMm: 24.3,
    coinTypeTags: ['silver', 'quarter', 'key-date', 'washington'],
    historyText: 'First year of Washington quarter series. Denver had lowest mintage. Issued for Washington\'s 200th birthday. Depression era limited production.',
    collectorNotes: 'Key date for Washington quarter collectors. Values $100+ circulated, $10,000+ gem uncirculated. 1932-S also valuable but higher mintage.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1932-d-25c/5793'],
    sources: [{ title: 'Washington Quarter Guide', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
]
