import type { Coin } from './types'

export const expandedRareCoins: Coin[] = [
  {
    id: 'coin-001',
    name: '1916-D Mercury Dime',
    issuerCountry: 'United States',
    denomination: '10 cents',
    year: 1916,
    mint: 'Denver',
    mintage: 264000,
    composition: '90% Silver, 10% Copper',
    diameterMm: 17.9,
    coinTypeTags: ['key-date', 'low-mintage', 'mercury-dime', 'silver'],
    historyText: 'First year of Mercury dime series designed by Adolph Weinman. Denver mint produced only 264,000 making it the key date of the series. Liberty wears winged cap symbolizing freedom of thought.',
    collectorNotes: 'Most valuable coin in Mercury dime series. Even well-worn examples valuable. Beware of counterfeits. Authenticate before purchasing. Values range from $1,000+ in Good condition to $30,000+ in Mint State.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1916-d-10c/4906'],
    sources: [{ title: 'PCGS CoinFacts', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-002',
    name: '1909-S VDB Lincoln Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1909,
    mint: 'San Francisco',
    mintage: 484000,
    composition: '95% Copper, 5% Tin and Zinc',
    diameterMm: 19,
    coinTypeTags: ['key-date', 'lincoln-cent', 'vdb', 'low-mintage'],
    historyText: 'First year of Lincoln cent. Designer Victor David Brenner\'s initials (VDB) on reverse caused controversy, leading to removal mid-year. San Francisco mint produced limited quantity before change.',
    collectorNotes: 'Holy grail for Lincoln cent collectors. Lowest mintage of VDB varieties. Check reverse for clear VDB initials at bottom. Values $700+ circulated, $1,500+ uncirculated. Most common date in search for valuable pennies.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1909-s-vdb-1c/2426'],
    sources: [{ title: 'NGC Coin Explorer', url: 'https://www.ngccoin.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-003',
    name: '1933 Saint-Gaudens Double Eagle',
    issuerCountry: 'United States',
    denomination: '$20 Gold',
    year: 1933,
    mint: 'Philadelphia',
    mintage: 445500,
    composition: '90% Gold, 10% Copper',
    diameterMm: 34,
    coinTypeTags: ['gold', 'legendary', 'forbidden', 'double-eagle'],
    historyText: 'Most famous coin in U.S. history. FDR banned gold ownership in 1933. Almost all were melted. Only one legally owned - sold for $7.59 million in 2002, $18.9 million in 2021.',
    collectorNotes: 'Illegal to own except the single Fenton specimen. Any others are subject to confiscation. Most valuable coin ever auctioned.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1933-20/9177'],
    sources: [{ title: 'Smithsonian Numismatics', url: 'https://www.si.edu/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-004',
    name: '1794 Flowing Hair Silver Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 1794,
    mint: 'Philadelphia',
    mintage: 1758,
    composition: '89.24% Silver, 10.76% Copper',
    diameterMm: 39.40,
    coinTypeTags: ['silver', 'first-year', 'flowing-hair', 'legendary'],
    historyText: 'First silver dollar struck by U.S. Mint. Believed to be among first coins struck for circulation. Historic significance as foundation of American coinage.',
    collectorNotes: 'Sold for $10 million in 2013, making it most expensive coin ever. Even worn examples worth six figures. Check for proper edge lettering.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1794-1/6851'],
    sources: [{ title: 'Heritage Auctions Archives', url: 'https://www.ha.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-005',
    name: '1913 Liberty Head Nickel',
    issuerCountry: 'United States',
    denomination: '5 cents',
    year: 1913,
    mint: 'Philadelphia',
    mintage: 5,
    composition: '75% Copper, 25% Nickel',
    diameterMm: 21.2,
    coinTypeTags: ['nickel', 'pattern', 'ultra-rare', 'mystery'],
    historyText: 'Only 5 known. Never officially released. Minted secretly after series ended. Mystery surrounds creation - possibly by rogue Mint employee.',
    collectorNotes: 'One of numismatics greatest mysteries. Each of 5 specimens has own history. Worth $3-5 million. Featured in Hawaii Five-O.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1913-5c/3882'],
    sources: [{ title: 'ANA Museum Collection', url: 'https://www.money.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-006',
    name: '1804 Draped Bust Silver Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 1804,
    mint: 'Philadelphia',
    mintage: 15,
    composition: '89.24% Silver, 10.76% Copper',
    diameterMm: 39.40,
    coinTypeTags: ['silver', 'king-of-coins', 'diplomatic-gift'],
    historyText: 'King of American Coins. Actually struck in 1834-35 as diplomatic gifts. Bears 1804 date but none made that year. 15 known specimens in three classes.',
    collectorNotes: 'Class I specimens worth $4-7 million. Class II and III also extremely valuable. Verify class and authenticity with major grading service.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1804-1/6889'],
    sources: [{ title: 'Bowers Numismatic Research', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-007',
    name: '1937-D 3-Legged Buffalo Nickel',
    issuerCountry: 'United States',
    denomination: '5 cents',
    year: 1937,
    mint: 'Denver',
    mintage: 5635000,
    composition: '75% Copper, 25% Nickel',
    diameterMm: 21.2,
    coinTypeTags: ['nickel', 'error', 'variety', 'buffalo'],
    historyText: 'Famous error from over-polished die removing buffalo\'s front leg. Die polishing removed design detail to extend die life, creating valued variety.',
    collectorNotes: 'Look for completely missing front leg. Normal wear shows faint leg. Values $500-$5,000+ depending on grade. Many counterfeits exist.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1937-d-5c-3-legs/3983'],
    sources: [{ title: 'NGC Variety Guide', url: 'https://www.ngccoin.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-008',
    name: '1943 Copper Lincoln Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1943,
    mint: 'Philadelphia',
    mintage: 40,
    composition: '95% Copper, 5% Tin and Zinc',
    diameterMm: 19,
    coinTypeTags: ['cent', 'error', 'wartime', 'copper'],
    historyText: 'In 1943 pennies made of steel to save copper for WWII. About 40 copper blanks accidentally struck. One of most famous U.S. mint errors.',
    collectorNotes: 'Worth $100,000-$1,000,000+. Many steel cents copper-plated to deceive. Weight test: copper weighs 3.11g vs steel 2.7g. Magnet test: copper non-magnetic.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1943-1c/2715'],
    sources: [{ title: 'U.S. Mint Error Coins Guide', url: 'https://www.usmint.gov/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-009',
    name: '1893-S Morgan Silver Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 1893,
    mint: 'San Francisco',
    mintage: 100000,
    composition: '90% Silver, 10% Copper',
    diameterMm: 38.1,
    coinTypeTags: ['silver', 'morgan', 'key-date', 'low-mintage'],
    historyText: 'Lowest mintage of business-strike Morgan dollars. Economic depression limited production. San Francisco produced only 100,000.',
    collectorNotes: 'Most valuable regular-issue Morgan. Values $3,000+ circulated, $100,000+ high grades. Essential for Morgan dollar collection completion.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1893-s-1/7226'],
    sources: [{ title: 'Morgan Dollar Reference', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-010',
    name: '1955 Doubled Die Lincoln Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1955,
    mint: 'Philadelphia',
    mintage: 24000,
    composition: '95% Copper, 5% Tin and Zinc',
    diameterMm: 19,
    coinTypeTags: ['cent', 'error', 'doubled-die', 'lincoln'],
    historyText: 'Most famous doubled die coin. Hub doubled during die creation process. Dramatic doubling visible on date and lettering. Released into circulation despite error.',
    collectorNotes: 'Look for clear doubling on "LIBERTY" and date. Values $1,000-$20,000+ depending on grade. Easily spotted with naked eye.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1955-1c-ddo-fs-101/37911'],
    sources: [{ title: 'Doubled Die Reference', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-011',
    name: '1969-S Doubled Die Lincoln Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1969,
    mint: 'San Francisco',
    mintage: 40,
    composition: '95% Copper, 5% Zinc',
    diameterMm: 19,
    coinTypeTags: ['cent', 'error', 'doubled-die', 'ultra-rare'],
    historyText: 'Extreme doubling on obverse, especially "LIBERTY" and "IN GOD WE TRUST". Only about 40 known. Mint attempted to destroy all specimens.',
    collectorNotes: 'Values $20,000-$100,000+. Sharp doubling throughout. Beware of the more common 1969 Philadelphia doubled die (worth much less).',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1969-s-1c-ddo-fs-101/38001'],
    sources: [{ title: 'Major Doubled Dies', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-012',
    name: '1932-D Washington Quarter',
    issuerCountry: 'United States',
    denomination: '25 cents',
    year: 1932,
    mint: 'Denver',
    mintage: 436800,
    composition: '90% Silver, 10% Copper',
    diameterMm: 24.3,
    coinTypeTags: ['silver', 'quarter', 'key-date', 'washington'],
    historyText: 'First year of Washington quarter series. Denver had lowest mintage. Issued for Washington\'s 200th birthday. Depression era limited production.',
    collectorNotes: 'Key date for Washington quarter collectors. Values $100+ circulated, $10,000+ gem uncirculated. 1932-S also valuable but higher mintage.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1932-d-25c/5793'],
    sources: [{ title: 'Washington Quarter Guide', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-013',
    name: '1787 Brasher Doubloon',
    issuerCountry: 'United States',
    denomination: 'Doubloon',
    year: 1787,
    mint: 'Brasher (Private)',
    mintage: 7,
    composition: '90% Gold',
    diameterMm: 32,
    coinTypeTags: ['gold', 'colonial', 'legendary', 'pre-mint'],
    historyText: 'One of earliest American gold coins struck by goldsmith Ephraim Brasher. Features his "EB" hallmark. Predates U.S. Mint establishment. Only 7 known examples exist.',
    collectorNotes: 'Extremely rare pre-federal coin. Sold for $7.4 million in 2011. Important piece of American numismatic history. Most are in museums.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/brasher-doubloon-eb-on-wing/99999'],
    sources: [{ title: 'Early American Coinage', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-014',
    name: '1822 Half Eagle',
    issuerCountry: 'United States',
    denomination: '$5 Gold',
    year: 1822,
    mint: 'Philadelphia',
    mintage: 17796,
    composition: '91.67% Gold, 8.33% Copper',
    diameterMm: 25,
    coinTypeTags: ['gold', 'ultra-rare', 'half-eagle'],
    historyText: 'Only 3 known survivors. Two are in Smithsonian collection. One privately owned specimen exists. Nearly entire mintage melted or lost.',
    collectorNotes: 'Rarest U.S. gold coin available to collectors (only 1 in private hands). Valued at $8+ million. Essential hole in any complete half eagle collection.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1822-5/8116'],
    sources: [{ title: 'Rare Gold Coinage', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-015',
    name: '1975 No S Roosevelt Dime',
    issuerCountry: 'United States',
    denomination: '10 cents',
    year: 1975,
    mint: 'San Francisco (Proof)',
    mintage: 2,
    composition: '75% Copper, 25% Nickel',
    diameterMm: 17.9,
    coinTypeTags: ['modern', 'error', 'proof', 'ultra-rare'],
    historyText: 'Missing mintmark on proof coin. Only 2 known examples. Accidentally struck without "S" mintmark from proof dies at San Francisco Mint.',
    collectorNotes: 'One of rarest modern U.S. coins. Valued $450,000+. Check all 1975 proof sets carefully. Missing mintmark is key identifier.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1975-no-s-10c/5159'],
    sources: [{ title: 'Modern Mint Errors', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-016',
    name: '2000 Sacagawea Dollar Mule',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 2000,
    mint: 'Philadelphia',
    mintage: 18,
    composition: 'Manganese Brass',
    diameterMm: 26.5,
    coinTypeTags: ['modern', 'error', 'mule', 'ultra-rare'],
    historyText: 'Dramatic error pairing Sacagawea dollar obverse with Washington quarter reverse. About 18 known. Resulted from incorrect die pairing at mint.',
    collectorNotes: 'Most dramatic modern U.S. mint error. Values $50,000-$100,000+. Reverse shows Washington quarter eagle design instead of eagle and stars.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/2000-p-sac-washington-quarter-mule/99999'],
    sources: [{ title: 'Major Mint Errors', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-017',
    name: '1974 Aluminum Lincoln Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1974,
    mint: 'Philadelphia',
    mintage: 1,
    composition: 'Aluminum',
    diameterMm: 19,
    coinTypeTags: ['pattern', 'experimental', 'aluminum'],
    historyText: 'Experimental cent struck in aluminum to save costs. Program abandoned. Most specimens destroyed. Only one confirmed in private hands.',
    collectorNotes: 'Technically illegal to own. Mint attempted to recall all examples. Extremely controversial among collectors. Featured in major legal battles.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1974-1c-aluminum/99999'],
    sources: [{ title: 'Pattern Coins', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-018',
    name: '2000-P Cheerios Sacagawea Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 2000,
    mint: 'Philadelphia',
    mintage: 5500,
    composition: 'Manganese Brass',
    diameterMm: 26.5,
    coinTypeTags: ['modern', 'variety', 'promotional'],
    historyText: 'Special prototype design distributed in Cheerios cereal boxes. Features enhanced tail feathers on eagle. Only 5,500 made as promotion before regular production.',
    collectorNotes: 'Look for detailed tail feathers on reverse eagle. Values $3,000-$10,000+ depending on grade. Most still circulating or in collections unknowingly.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/2000-p-sac-cheerios-reverse/149476'],
    sources: [{ title: 'Sacagawea Dollar Varieties', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-019',
    name: '1932-S Washington Quarter',
    issuerCountry: 'United States',
    denomination: '25 cents',
    year: 1932,
    mint: 'San Francisco',
    mintage: 408000,
    composition: '90% Silver, 10% Copper',
    diameterMm: 24.3,
    coinTypeTags: ['silver', 'quarter', 'key-date'],
    historyText: 'First year Washington quarter from San Francisco. Second scarcest in series after 1932-D. Depression-era low mintage.',
    collectorNotes: 'Essential date for quarter collectors. Values $80+ circulated, $5,000+ uncirculated. Slightly less valuable than Denver mint.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1932-s-25c/5794'],
    sources: [{ title: 'Washington Quarters', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-020',
    name: '1916 Standing Liberty Quarter',
    issuerCountry: 'United States',
    denomination: '25 cents',
    year: 1916,
    mint: 'Philadelphia',
    mintage: 52000,
    composition: '90% Silver, 10% Copper',
    diameterMm: 24.3,
    coinTypeTags: ['silver', 'quarter', 'key-date', 'type-1'],
    historyText: 'First year and lowest mintage of Standing Liberty quarter series. Design features Liberty with exposed breast, modified in 1917 due to controversy.',
    collectorNotes: 'Most valuable quarter in series. Values $2,000+ circulated, $10,000+ uncirculated. Type 1 design makes it especially desirable.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1916-25c/5704'],
    sources: [{ title: 'Standing Liberty Quarters', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-021',
    name: '1894-S Barber Dime',
    issuerCountry: 'United States',
    denomination: '10 cents',
    year: 1894,
    mint: 'San Francisco',
    mintage: 24,
    composition: '90% Silver, 10% Copper',
    diameterMm: 17.9,
    coinTypeTags: ['silver', 'legendary', 'barber', 'ultra-rare'],
    historyText: 'Only 24 struck, 9 known to exist. Mystery surrounds small mintage - possibly struck as gifts for banker friends. Most famous dime in numismatics.',
    collectorNotes: 'Valued at $1-2 million each. Story tells Mint Superintendent gave them to friends, one spent by daughter for ice cream. Holy grail for dime collectors.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1894-s-10c/4846'],
    sources: [{ title: 'Legendary Rarities', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-022',
    name: '1838-O Capped Bust Half Dollar',
    issuerCountry: 'United States',
    denomination: '50 cents',
    year: 1838,
    mint: 'New Orleans',
    mintage: 10,
    composition: '89.24% Silver, 10.76% Copper',
    diameterMm: 30.6,
    coinTypeTags: ['silver', 'first-year', 'ultra-rare'],
    historyText: 'First coins struck at New Orleans Mint. Only 10 produced as test strikes before official operations began. First branch mint issue.',
    collectorNotes: 'Extremely rare first-year issue. Valued $500,000+. Important in U.S. Mint history as first branch mint coinage.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1838-o-50c/6177'],
    sources: [{ title: 'Branch Mint Rarities', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-023',
    name: '1870-S Seated Liberty Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 1870,
    mint: 'San Francisco',
    mintage: 12,
    composition: '90% Silver, 10% Copper',
    diameterMm: 38.1,
    coinTypeTags: ['silver', 'legendary', 'seated-liberty'],
    historyText: 'About 12 struck for San Francisco Mint cornerstone ceremony. Most lost when building demolished. Only 1 or 2 known to exist.',
    collectorNotes: 'One of rarest regular-issue U.S. coins. Worth millions. Legend says examples buried in cornerstone lost forever.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1870-s-1/7000'],
    sources: [{ title: 'Seated Liberty Dollars', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-024',
    name: '1927-D Saint-Gaudens Double Eagle',
    issuerCountry: 'United States',
    denomination: '$20 Gold',
    year: 1927,
    mint: 'Denver',
    mintage: 180000,
    composition: '90% Gold, 10% Copper',
    diameterMm: 34,
    coinTypeTags: ['gold', 'double-eagle', 'key-date'],
    historyText: 'Lowest mintage of Denver Saint-Gaudens twenties. Most melted in 1930s gold recall. Beautiful Augustus Saint-Gaudens design.',
    collectorNotes: 'Key date in series. Values $15,000+ circulated, $100,000+ uncirculated. Rare in high grades.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1927-d-20/9187'],
    sources: [{ title: 'Saint-Gaudens Gold', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-025',
    name: '1796 Draped Bust Quarter',
    issuerCountry: 'United States',
    denomination: '25 cents',
    year: 1796,
    mint: 'Philadelphia',
    mintage: 6146,
    composition: '89.24% Silver, 10.76% Copper',
    diameterMm: 27.5,
    coinTypeTags: ['silver', 'first-year', 'draped-bust'],
    historyText: 'First quarter ever struck by U.S. Mint. Only year of Draped Bust design without stars on obverse. Extremely low mintage.',
    collectorNotes: 'First U.S. quarter makes it highly desirable. Values $5,000+ even in low grades, $100,000+ in high grades.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1796-25c/5310'],
    sources: [{ title: 'Early Quarter Dollars', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-026',
    name: '1861 Confederate Half Dollar',
    issuerCountry: 'Confederate States',
    denomination: '50 cents',
    year: 1861,
    mint: 'New Orleans',
    mintage: 4,
    composition: '90% Silver, 10% Copper',
    diameterMm: 30.6,
    coinTypeTags: ['confederate', 'ultra-rare', 'civil-war'],
    historyText: 'Only 4 struck using Confederate reverse die. Struck at New Orleans Mint briefly controlled by Confederacy. Original reverse die used to create restrikes.',
    collectorNotes: 'Extremely rare Confederate issue. Original 4 worth millions. Later restrikes also valuable but less so.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1861-50c-confederate/99999'],
    sources: [{ title: 'Confederate Coinage', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-027',
    name: '1866 No Motto Seated Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 1866,
    mint: 'Philadelphia',
    mintage: 60,
    composition: '90% Silver, 10% Copper',
    diameterMm: 38.1,
    coinTypeTags: ['silver', 'transitional', 'error'],
    historyText: 'Transitional error - struck without new "In God We Trust" motto required in 1866. Only about 60 made before error caught.',
    collectorNotes: 'Rare transitional variety. Values $25,000-$100,000+. Important piece showing motto transition period.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1866-1-no-motto/6959'],
    sources: [{ title: 'Seated Dollar Varieties', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-028',
    name: '1942/1 Mercury Dime',
    issuerCountry: 'United States',
    denomination: '10 cents',
    year: 1942,
    mint: 'Philadelphia',
    mintage: 205432329,
    composition: '90% Silver, 10% Copper',
    diameterMm: 17.9,
    coinTypeTags: ['silver', 'overdate', 'error'],
    historyText: 'Famous overdate variety - 1942 struck over 1941 die. Clearly visible "1" under "2" in date. Most famous Mercury dime variety.',
    collectorNotes: 'Look for traces of "1" below "2" in date. Values $500+ circulated, $5,000+ uncirculated. Denver version (1942/1-D) also exists.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1942-1-10c/5050'],
    sources: [{ title: 'Mercury Dime Varieties', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-029',
    name: '1921 Peace Dollar',
    issuerCountry: 'United States',
    denomination: '$1',
    year: 1921,
    mint: 'Philadelphia',
    mintage: 1006473,
    composition: '90% Silver, 10% Copper',
    diameterMm: 38.1,
    coinTypeTags: ['silver', 'first-year', 'peace', 'high-relief'],
    historyText: 'First year of Peace dollar series. High relief design celebrating WWI peace. Relief lowered in 1922 due to production difficulties.',
    collectorNotes: 'Most valuable regular-issue Peace dollar. High relief makes it desirable. Values $200+ circulated, $1,000+ uncirculated.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1921-1/7356'],
    sources: [{ title: 'Peace Dollar Guide', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'coin-030',
    name: '1909-S Indian Head Cent',
    issuerCountry: 'United States',
    denomination: '1 cent',
    year: 1909,
    mint: 'San Francisco',
    mintage: 309000,
    composition: '95% Copper, 5% Tin and Zinc',
    diameterMm: 19,
    coinTypeTags: ['copper', 'last-year', 'key-date'],
    historyText: 'Last year of Indian Head cent series from San Francisco. Lowest San Francisco mintage in series. Final year before Lincoln cent.',
    collectorNotes: 'Key date for Indian cent collectors. Values $400+ circulated, $2,000+ uncirculated. Essential for completing set.',
    whereToFindLinks: ['https://www.pcgs.com/coinfacts/coin/1909-s-1c/2235'],
    sources: [{ title: 'Indian Head Cents', url: 'https://www.pcgs.com/', retrievedAt: '2024-01-15' }],
  },
]
