import type { Gemstone } from './types'

export const expandedGemstones: Gemstone[] = [
  {
    id: 'gem-001',
    name: 'Arkansas Quartz Crystal',
    type: 'crystal',
    mohs: 7,
    colors: ['Clear', 'White', 'Smoky'],
    formation: 'Hydrothermal crystals formed 300 million years ago in Ouachita Mountains. Recognized as Arkansas state mineral.',
    whereFoundRegions: ['Arkansas (Ouachita Mountains)', 'Hot Springs area'],
    ethicalCollectingNotes: 'Visit fee-dig crystal mines where you keep what you find. Mines like Wegner Crystal Mines and Ron Coleman Mining allow ethical collecting. Never collect from protected land without permission.',
    whereToBuyNotes: 'Purchase from Arkansas crystal mines directly, or reputable mineral shows. Expect $10-50 for nice specimens. Ensure sourced from legal dig sites.',
    sources: [{ title: 'Arkansas Geological Survey', url: 'https://www.geology.arkansas.gov/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-002',
    name: 'Lake Superior Agate',
    type: 'gem',
    mohs: 6.5,
    colors: ['Red', 'Orange', 'Yellow', 'Brown banding'],
    formation: 'Volcanic activity 1.1 billion years ago. Iron oxidation creates striking red bands. Glaciers distributed them across Great Lakes region.',
    whereFoundRegions: ['Minnesota', 'Wisconsin', 'Michigan (Lake Superior shores)'],
    ethicalCollectingNotes: 'Collect from public beaches and gravel pits with permission. Minnesota state gemstone. Best hunting after storms expose new material.',
    whereToBuyNotes: 'Find at rock shops in Minnesota/Wisconsin. Prices range $5-100+ depending on size and banding. Look for authentic Great Lakes origin certification.',
    sources: [{ title: 'Minnesota DNR Mineral Resources', url: 'https://www.dnr.state.mn.us/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-003',
    name: 'Petoskey Stone',
    type: 'gem',
    mohs: 4,
    colors: ['Gray', 'Brown', 'Coral patterns'],
    formation: 'Fossilized coral from Devonian period (350 million years ago). Hexagonal patterns are ancient coral polyps. Found in glacial deposits.',
    whereFoundRegions: ['Michigan', 'Lake Michigan shoreline', 'Lake Huron'],
    ethicalCollectingNotes: 'Michigan state stone. Collect from public beaches. Best found when wet. Not permitted to remove from state parks without license.',
    whereToBuyNotes: 'Common in Michigan gift shops and rock stores. Prices $5-50 depending on size and pattern clarity. Polished specimens show best coral detail.',
    sources: [{ title: 'Michigan Geological Survey', url: 'https://www.michigan.gov/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-004',
    name: 'Yooperlite',
    type: 'crystal',
    mohs: 5.5,
    colors: ['Gray', 'Orange glow under UV'],
    formation: 'Syenite rock with sodalite inclusions. Canadian Shield origin. Discovered in 2017. Fluoresces bright orange under UV light.',
    whereFoundRegions: ['Michigan Upper Peninsula', 'Lake Superior beaches'],
    ethicalCollectingNotes: 'Recently discovered collector stone. Found on public beaches. Best hunted at night with UV flashlight. Glows bright orange.',
    whereToBuyNotes: 'Increasingly popular. Prices $10-100+ for specimens. UV flashlight essential for identification. Check Michigan mineral dealers.',
    sources: [{ title: 'Yooperlite Discovery', url: 'https://www.yooperlites.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-005',
    name: 'Montana Sapphire',
    type: 'gem',
    mohs: 9,
    colors: ['Blue', 'Green', 'Yellow', 'Purple', 'Pink'],
    formation: 'Corundum crystals formed in metamorphic rocks. Found in gravel deposits from erosion. Heat treatment enhances color.',
    whereFoundRegions: ['Montana (Rock Creek', 'Missouri River', 'Yogo Gulch)'],
    ethicalCollectingNotes: 'Fee-dig mines available. Gem Mountain and other sites allow bucket digging. Keep what you find. Support ethical mining operations.',
    whereToBuyNotes: 'Montana sapphires known for unique colors. Prices $50-$1000+ per carat depending on quality. Yogo sapphires most valuable variety.',
    sources: [{ title: 'Montana Bureau of Mines', url: 'https://www.mbmg.mtech.edu/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-006',
    name: 'Oregon Sunstone',
    type: 'gem',
    mohs: 6.5,
    colors: ['Clear', 'Yellow', 'Pink', 'Red', 'Green with copper schiller'],
    formation: 'Plagioclase feldspar with copper inclusions. Volcanic origin. Copper creates metallic glitter called schiller effect.',
    whereFoundRegions: ['Oregon (Harney County', 'Lake County)'],
    ethicalCollectingNotes: 'Oregon state gemstone. Public collecting areas available on BLM land. Free collecting with reasonable limits. Respect claim boundaries.',
    whereToBuyNotes: 'Copper-bearing variety most valuable. Prices $20-$500+ per stone. Oregon sunstone with red color and strong schiller most prized.',
    sources: [{ title: 'Oregon Sunstone Public Collection Area', url: 'https://www.blm.gov/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-007',
    name: 'Turquoise',
    type: 'gem',
    mohs: 5.5,
    colors: ['Blue', 'Green', 'Blue-green'],
    formation: 'Copper aluminum phosphate mineral. Forms in arid regions through water percolation. Matrix patterns from host rock.',
    whereFoundRegions: ['Southwest USA', 'Nevada', 'Arizona', 'New Mexico'],
    ethicalCollectingNotes: 'Most quality deposits on private or claimed land. Respect mining claims. Purchase from reputable dealers ensuring ethical sourcing.',
    whereToBuyNotes: 'Sleeping Beauty (AZ) and Lone Mountain (NV) among finest. Prices $5-$500+ per stone. Natural unstabilized turquoise most valuable.',
    sources: [{ title: 'Turquoise Museum', url: 'https://www.turquoisemuseum.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-008',
    name: 'Fire Agate',
    type: 'gem',
    mohs: 7,
    colors: ['Brown with rainbow iridescence'],
    formation: 'Layered chalcedony with iron oxide creating iridescence. Forms in volcanic environments. Thin layers create fire effect.',
    whereFoundRegions: ['Arizona', 'New Mexico', 'California', 'Mexico'],
    ethicalCollectingNotes: 'Most sites are claimed. Fee-dig locations available in Arizona. Slaughter Mountain area known for fire agate. Respect private property.',
    whereToBuyNotes: 'Quality fire with strong color brings premium prices. Range $50-$1000+ depending on fire coverage and intensity. Desert USA source.',
    sources: [{ title: 'Fire Agate Mining', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-009',
    name: 'Amethyst',
    type: 'crystal',
    mohs: 7,
    colors: ['Purple', 'Violet', 'Deep purple'],
    formation: 'Quartz colored by iron and natural radiation. Forms in geodes and veins. Deep color from radiation exposure over millions of years.',
    whereFoundRegions: ['Uruguay', 'Brazil', 'North Carolina', 'Arizona'],
    ethicalCollectingNotes: 'Jackson Crossroads (GA) and Four Peaks (AZ) offer fee-dig opportunities. Most commercial material from South America mines.',
    whereToBuyNotes: 'Prices vary wildly $5-$500+ based on color depth and clarity. Siberian amethyst (deep purple) most valuable. Check gem shows.',
    sources: [{ title: 'International Gem Society', url: 'https://www.gemsociety.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-010',
    name: 'Moldavite',
    type: 'gem',
    mohs: 5.5,
    colors: ['Green', 'Olive green', 'Brown-green'],
    formation: 'Natural glass formed by meteorite impact 15 million years ago. Tektite from Nördlinger Ries crater event. Only found in Czech Republic.',
    whereFoundRegions: ['Czech Republic (Bohemia', 'Moravia)'],
    ethicalCollectingNotes: 'All material from Czech Republic. Commercial collecting only. Many fakes on market. Certificate of authenticity essential.',
    whereToBuyNotes: 'Increasingly rare and expensive. Prices $20-$100+ per gram. Sculptured texture authentic. Smooth stones likely fake. Buy from certified dealers.',
    sources: [{ title: 'Moldavite Authenticity', url: 'https://www.moldavite.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-011',
    name: 'Labradorite',
    type: 'gem',
    mohs: 6,
    colors: ['Gray', 'Black with blue', 'green', 'gold flash'],
    formation: 'Plagioclase feldspar exhibiting labradorescence (color flash). Caused by light interference in twinned layers. Named after Labrador, Canada.',
    whereFoundRegions: ['Labrador Canada', 'Madagascar', 'Finland', 'Russia'],
    ethicalCollectingNotes: 'Spectrolite (Finnish variety) highly prized. Most commercial material from Madagascar. Check ethical mining certifications.',
    whereToBuyNotes: 'Quality depends on flash strength and colors. Prices $5-$100+ per specimen. Full-spectrum flash most valuable. Common at gem shows.',
    sources: [{ title: 'Labradorite Properties', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-012',
    name: 'Chrysocolla',
    type: 'gem',
    mohs: 2.5,
    colors: ['Blue', 'Green', 'Turquoise blue'],
    formation: 'Copper silicate formed in oxidation zones of copper deposits. Often intermixed with malachite and azurite. Soft material.',
    whereFoundRegions: ['Arizona', 'New Mexico', 'Peru', 'Democratic Republic of Congo'],
    ethicalCollectingNotes: 'Found near copper mines. Gem-quality chrysocolla often stabilized for durability. Ensure ethical sourcing from established mines.',
    whereToBuyNotes: 'Gem silica (translucent variety) most valuable at $50-$500+ per carat. Common opaque material $5-$50. Check Arizona dealers.',
    sources: [{ title: 'Copper Minerals Guide', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-013',
    name: 'Herkimer Diamond',
    type: 'crystal',
    mohs: 7.5,
    colors: ['Clear', 'Water clear'],
    formation: 'Double-terminated quartz crystals from dolostone. Naturally faceted appearance. Formed 500 million years ago in cavities.',
    whereFoundRegions: ['Herkimer County New York', 'Mohawk River Valley'],
    ethicalCollectingNotes: 'Fee-dig mines in Herkimer County allow collecting. Herkimer Diamond Mines and Ace of Diamonds popular sites. Keep what you find.',
    whereToBuyNotes: 'Prices based on clarity and size. $5-$100+ per crystal. Water-clear double-terminated specimens most prized. Visit Herkimer area.',
    sources: [{ title: 'Herkimer Diamond Info', url: 'https://www.herkimerdiamond.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-014',
    name: 'Benitoite',
    type: 'gem',
    mohs: 6.5,
    colors: ['Blue', 'Purple', 'Colorless'],
    formation: 'Rare barium titanium silicate. Only gem-quality source in California. Forms in hydrothermal serpentinite. Fluoresces under UV.',
    whereFoundRegions: ['San Benito County California'],
    ethicalCollectingNotes: 'California state gemstone. Source mine closed to collecting. All material from old production. Extremely rare gemstone.',
    whereToBuyNotes: 'One of rarest gemstones. Prices $1000-$10,000+ per carat for clean gems. Investment-grade gem. Only from established dealers.',
    sources: [{ title: 'Benitoite Rarity', url: 'https://www.gia.edu/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-015',
    name: 'Malachite',
    type: 'gem',
    mohs: 3.5,
    colors: ['Green', 'Banded green'],
    formation: 'Copper carbonate with distinctive banding. Forms in oxidized copper deposits. Layers create bull\'s-eye and swirl patterns.',
    whereFoundRegions: ['Democratic Republic of Congo', 'Russia', 'Arizona', 'Australia'],
    ethicalCollectingNotes: 'Much commercial material from DRC. Ensure ethical sourcing and conflict-free certification. Russian material historically significant.',
    whereToBuyNotes: 'Prices vary by size and pattern quality. $10-$500+ for specimens. Fibrous chatoyant material rare. Check ethical certifications.',
    sources: [{ title: 'Malachite Deposits', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-016',
    name: 'Azurite',
    type: 'gem',
    mohs: 3.5,
    colors: ['Azure blue', 'Deep blue'],
    formation: 'Copper carbonate mineral. Forms with malachite in copper deposits. Intense blue from copper content. Often converts to malachite over time.',
    whereFoundRegions: ['Arizona', 'New Mexico', 'Morocco', 'China'],
    ethicalCollectingNotes: 'Bisbee, Arizona famous for azurite specimens. Most mines closed. Purchase from reputable dealers with source documentation.',
    whereToBuyNotes: 'Crystal specimens $20-$500+. Azurmalachite combinations popular. Historic Bisbee material premium. Moroccan nodules common at shows.',
    sources: [{ title: 'Azurite Localities', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-017',
    name: 'Citrine',
    type: 'crystal',
    mohs: 7,
    colors: ['Yellow', 'Orange', 'Golden'],
    formation: 'Quartz colored by iron. Natural citrine rare - most is heat-treated amethyst. True citrine from natural heat in earth or natural radiation.',
    whereFoundRegions: ['Brazil', 'Madagascar', 'Russia', 'Spain'],
    ethicalCollectingNotes: 'Most "citrine" on market is heated amethyst. Natural citrine paler yellow. Ask for treatment disclosure when purchasing.',
    whereToBuyNotes: 'Heat-treated material $5-$50. Natural citrine $50-$500+ per stone. Madeira citrine (deep orange) most valuable. Verify treatment status.',
    sources: [{ title: 'Citrine Authenticity', url: 'https://www.gia.edu/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-018',
    name: 'Fluorite',
    type: 'crystal',
    mohs: 4,
    colors: ['Purple', 'Green', 'Blue', 'Yellow', 'Clear', 'Rainbow'],
    formation: 'Calcium fluoride in hydrothermal deposits. Wide color range from trace elements. Cubic crystal form. Fluorescence namesake.',
    whereFoundRegions: ['Illinois', 'China', 'Mexico', 'England'],
    ethicalCollectingNotes: 'Illinois Cave-in-Rock district famous. Rosiclare fluorite mines historical. Modern material often Chinese. Collect with permission.',
    whereToBuyNotes: 'Collector specimens $10-$500+ based on size and color. Blue John (English) rare and valuable. Chinese cubic crystals affordable.',
    sources: [{ title: 'Fluorite Varieties', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-019',
    name: 'Rhodochrosite',
    type: 'gem',
    mohs: 3.5,
    colors: ['Pink', 'Red', 'Rose red with white bands'],
    formation: 'Manganese carbonate in hydrothermal veins. Banding creates beautiful patterns. Associated with silver mines.',
    whereFoundRegions: ['Colorado', 'Argentina', 'Peru', 'South Africa'],
    ethicalCollectingNotes: 'Colorado state mineral. Sweet Home Mine specimens legendary. Mine closed - existing material valuable. Argentine material available.',
    whereToBuyNotes: 'Colorado stalactite specimens $100-$10,000+. Argentine material more affordable $20-$200. Gem-quality rare and expensive.',
    sources: [{ title: 'Rhodochrosite Deposits', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-020',
    name: 'Amazonite',
    type: 'gem',
    mohs: 6,
    colors: ['Blue-green', 'Turquoise', 'Green'],
    formation: 'Potassium feldspar colored by lead. Forms in pegmatites. Microcline variety. Color from lead and water in crystal structure.',
    whereFoundRegions: ['Colorado', 'Virginia', 'Russia', 'Madagascar'],
    ethicalCollectingNotes: 'Pikes Peak Colorado famous for quality material. Lake George area accessible with permission. Madagascar now major source.',
    whereToBuyNotes: 'Colorado material premium quality. Prices $10-$200+ for specimens. Deep blue-green most valuable. Common at rock shows.',
    sources: [{ title: 'Amazonite Localities', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-021',
    name: 'Rhodonite',
    type: 'gem',
    mohs: 5.5,
    colors: ['Pink', 'Red with black manganese veins'],
    formation: 'Manganese silicate in metamorphic and hydrothermal deposits. Black dendrites from manganese oxide. Massive and crystalline forms.',
    whereFoundRegions: ['Massachusetts', 'Russia', 'Australia', 'Peru'],
    ethicalCollectingNotes: 'Massachusetts state gem from Franklin quarries. Russian material historically significant. Transparent crystals rare and valuable.',
    whereToBuyNotes: 'Massive material $5-$50. Gem-quality crystals $50-$500+ per stone. Russian transparent crystals extremely rare and valuable.',
    sources: [{ title: 'Rhodonite Varieties', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-022',
    name: 'Selenite',
    type: 'crystal',
    mohs: 2,
    colors: ['Clear', 'White', 'Peach'],
    formation: 'Gypsum variety forming large transparent crystals. Evaporite mineral from ancient seas. Desert roses and satin spar varieties.',
    whereFoundRegions: ['Mexico', 'Morocco', 'Oklahoma', 'New Mexico'],
    ethicalCollectingNotes: 'Oklahoma state rock (selenite roses). Cave of Swords in Mexico has giant crystals. Respect collecting boundaries.',
    whereToBuyNotes: 'Very affordable. Small pieces $5-$20. Large specimens $50-$200+. Desert roses popular. Handle carefully - very soft and fragile.',
    sources: [{ title: 'Selenite Formations', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-023',
    name: 'Larimar',
    type: 'gem',
    mohs: 5,
    colors: ['Sky blue', 'Turquoise blue', 'Blue with white'],
    formation: 'Blue variety of pectolite. Only found in Dominican Republic. Volcanic origin. Copper gives blue color.',
    whereFoundRegions: ['Dominican Republic (Barahona Province)'],
    ethicalCollectingNotes: 'Only source in world - Dominican Republic. Mining controlled. Ensure purchases from legitimate Dominican dealers. Many fakes exist.',
    whereToBuyNotes: 'Prices $5-$200+ per piece based on color intensity. Volcanic blue most prized. Buy from certified Dominican sources to avoid fakes.',
    sources: [{ title: 'Larimar Official', url: 'https://www.larimar.com/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-024',
    name: 'Charoite',
    type: 'gem',
    mohs: 5,
    colors: ['Purple', 'Lavender', 'Violet with swirls'],
    formation: 'Rare silicate found only in Russia. Formed by alteration of limestone by alkaline intrusion. Fibrous structure creates swirling patterns.',
    whereFoundRegions: ['Sakha Republic Russia (Murun Mountains)'],
    ethicalCollectingNotes: 'Single source in world. Russian controlled mining. Material becoming scarcer. Verify authentic Russian origin.',
    whereToBuyNotes: 'Prices $20-$200+ for specimens. Deep purple with chatoyancy most valuable. Source may be depleted soon - collectible.',
    sources: [{ title: 'Charoite Rarity', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-025',
    name: 'Sugilite',
    type: 'gem',
    mohs: 6,
    colors: ['Purple', 'Pink', 'Violet'],
    formation: 'Rare cyclosilicate discovered in 1944. Major deposit in South Africa. Manganese gives purple color. Massive habit most common.',
    whereFoundRegions: ['South Africa', 'Japan', 'Italy'],
    ethicalCollectingNotes: 'South African material is primary source. Gel sugilite most valuable. Ensure ethical mining practices and fair trade.',
    whereToBuyNotes: 'Quality varies greatly. $10-$500+ based on color and translucency. Royal purple gel sugilite most expensive. Check gem shows.',
    sources: [{ title: 'Sugilite Properties', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-026',
    name: 'Pietersite',
    type: 'gem',
    mohs: 7,
    colors: ['Blue', 'Gold', 'Brown', 'Red with chatoyancy'],
    formation: 'Brecciated tiger\'s eye and hawk\'s eye. Folded and reformed creating swirling patterns. Chatoyant effect from fibrous structure.',
    whereFoundRegions: ['Namibia', 'China'],
    ethicalCollectingNotes: 'Namibian material original discovery. Chinese material more recent. Namibian source possibly depleted. Verify origin.',
    whereToBuyNotes: 'Namibian pietersite premium quality. Prices $50-$500+ for specimens. Blue flash most desirable. Chinese material more affordable.',
    sources: [{ title: 'Pietersite Varieties', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-027',
    name: 'Snowflake Obsidian',
    type: 'gem',
    mohs: 5.5,
    colors: ['Black with white snowflake patterns'],
    formation: 'Volcanic glass with cristobalite inclusions. Rapid cooling creates glass. White inclusions from crystallization during cooling.',
    whereFoundRegions: ['Utah', 'Nevada', 'Mexico'],
    ethicalCollectingNotes: 'Common in volcanic areas. Often found on public land with permits. Respect collecting regulations and claim boundaries.',
    whereToBuyNotes: 'Abundant and affordable. $5-$30 for most pieces. Large specimens with good patterns $50-$100. Popular for lapidary work.',
    sources: [{ title: 'Obsidian Varieties', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-028',
    name: 'Rainbow Obsidian',
    type: 'gem',
    mohs: 5.5,
    colors: ['Black with rainbow sheen'],
    formation: 'Volcanic glass with nanoparticle layers creating iridescence. Extremely rapid cooling. Thin layers cause light interference.',
    whereFoundRegions: ['Mexico', 'Oregon'],
    ethicalCollectingNotes: 'Mexican rainbow obsidian most colorful. Oregon material more subtle. Collect with landowner permission.',
    whereToBuyNotes: 'More valuable than common obsidian. Prices $20-$200+ based on color strength. Strong rainbow effect commands premium.',
    sources: [{ title: 'Rainbow Obsidian', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-029',
    name: 'Spirit Quartz',
    type: 'crystal',
    mohs: 7,
    colors: ['Purple', 'White', 'Yellow', 'Smoky covered in tiny crystals'],
    formation: 'Quartz covered in second generation crystal points. Drusy coating on larger crystal. From South Africa primarily.',
    whereFoundRegions: ['South Africa (Magaliesberg Mountains)'],
    ethicalCollectingNotes: 'Primarily South African. Also called cactus quartz or porcupine quartz. Ensure ethical South African mining sources.',
    whereToBuyNotes: 'Prices $20-$200+ based on size and coating. Purple amethyst variety most popular. Quality depends on coverage and color.',
    sources: [{ title: 'Spirit Quartz Info', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
  {
    id: 'gem-030',
    name: 'Apache Tears',
    type: 'gem',
    mohs: 5.5,
    colors: ['Black', 'Smoky brown when backlit'],
    formation: 'Rounded nodules of obsidian. Forms from volcanic lava cooling. Named for Native American legend. Translucent when thin.',
    whereFoundRegions: ['Arizona', 'Nevada', 'New Mexico'],
    ethicalCollectingNotes: 'Found in Southwest desert regions. Often on public land with proper permits. Respect Native American cultural sites.',
    whereToBuyNotes: 'Inexpensive and common. $5-$20 for typical specimens. Larger translucent pieces $30-$50. Popular collector item.',
    sources: [{ title: 'Apache Tears Legend', url: 'https://www.mindat.org/', retrievedAt: '2024-01-15' }],
  },
]
